# Libraries

In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import seaborn as sns


from sklearn.metrics import (
    silhouette_score,
    davies_bouldin_score,
    calinski_harabasz_score
)

from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score

In [2]:
# dispongo la carpeta con funciones e importo ternara. 
from pathlib import Path
import sys

# Obtiene la ruta del directorio actual y sube un nivel (.parent)
raiz_proyecto = Path().resolve().parent

# Agrega la ruta al sistema si no está ya incluida
if str(raiz_proyecto) not in sys.path:
  sys.path.append(str(raiz_proyecto))

# Importa tu librería o módulo
from funciones.ternaria import ternaria

# URLs y Constantes

In [3]:
BASE_URL = os.path.join('/mnt/', 'c')
BASE_DATA_URL = os.path.join('/mnt/', 'e')
COMP_URL = os.path.join(BASE_URL, 'Users', 'marco', 'Desktop', 'MASTER', 'MASTER', 'DMEyF', 'COMP1')
DATA_FOLDER = os.path.join(BASE_DATA_URL, 'DATASETS', 'DMEyF')
DATA_URL = os.path.join(DATA_FOLDER, 'competencia_01_crudo.csv')
DATA_TERNARIA_URL = os.path.join(DATA_FOLDER, 'competencia_01_ternaria.csv')

SEED = 230047

# UTILS

In [4]:
def van_dongen_normalized(contingency):
    n = contingency.values.sum()
    sum_max_rows = contingency.max(axis=1).sum()  # para cada label, max sobre clusters
    sum_max_cols = contingency.max(axis=0).sum()  # para cada cluster, max sobre labels
    max_row_total = contingency.sum(axis=1).max()
    max_col_total = contingency.sum(axis=0).max()
    
    vdn = (2*n - sum_max_rows - sum_max_cols) / (2*n - max_row_total - max_col_total)
    return vdn

# LEEMOS DATOS

In [5]:
df = pd.read_csv(
    DATA_TERNARIA_URL,
    dtype={'numero_de_cliente': 'int32', 'foto_mes': 'int32'}
)

/tmp/ipykernel_3150/3175415450.py:1: DtypeWarning: Columns (0: ternaria) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

# ANALISIS

In [6]:
mask_baja = df['ternaria'].str.contains('BAJA')

## Clustering sobre varialbles con sparcity menor al 90%

In [45]:
proporcion_ceros = (
    df.loc[mask_baja].select_dtypes(include="number")
      .eq(0)
      .sum()
      .div(len(df.loc[mask_baja]))
      .sort_values(ascending=False)
)
sparse_columns_09 = []
non_sparse_columns_09 = []
sparse_columns_08 = []
non_sparse_columns_08 = []
sparse_columns_07 = []
non_sparse_columns_07 = []
sparse_columns_06 = []
non_sparse_columns_06 = []
sparse_columns_05 = []
non_sparse_columns_05 = []
for columna in proporcion_ceros.items():
    if columna[1]>.9:
        sparse_columns_09.append(columna[0])
    else :
        non_sparse_columns_09.append(columna[0])
    if columna[1]>.8:
        sparse_columns_08.append(columna[0])
    else :
        non_sparse_columns_08.append(columna[0])
    if columna[1]>.7:
        sparse_columns_07.append(columna[0])
    else :
        non_sparse_columns_07.append(columna[0])
    if columna[1]>.6:
        sparse_columns_06.append(columna[0])
    else :
        non_sparse_columns_06.append(columna[0])
    if columna[1]>.5:
        sparse_columns_05.append(columna[0])
    else :
        non_sparse_columns_05.append(columna[0])

54 70 76
101 85 79

## K-Means

In [86]:
# columnas que no tienen valor informativo
columnas_excluir = [
    "numero_de_cliente",
    "foto_mes",
    "ternaria"
]
# Siempre agrego n registros de no baja para ver si el clustering los agrupa separado de los demas. 
def get_random_continua(k, mask_baja):
    indices_random_continua = (
        df.loc[df["ternaria"] == "continua"]
        .sample(
            n=round(mask_baja.sum() / k),
            random_state=SEED
        )
        .index)
    mask_random_continua = df.index.isin(indices_random_continua)
    return mask_random_continua

sparsity_rates = [0.3, .4, .5,  .6, .7, .8 , .9]
ks = [3,4,5,6]
resultados = []
dfs_baja = {}
for rate in sparsity_rates:
    sparse_columns = []
    non_sparse_columns = []  
    for columna in proporcion_ceros.items():
        if columna[1]>rate:
            sparse_columns.append(columna[0])
        else :
            non_sparse_columns.append(columna[0])
    _columnas_excluir = columnas_excluir + [x for x in sparse_columns]
    for k in ks:
        # agrego registros q no son de baja, quiero ver si el clustering los distingue
        mask_random = get_random_continua(k,mask_baja)
        df_baja = df.loc[mask_baja|mask_random].copy()
        df_baja.fillna(0, inplace=True) #naively filll with 0s
        labels_reales = df_baja['ternaria']
        X = df_baja.drop(columns = _columnas_excluir).select_dtypes(include='number')
        X_escalado = StandardScaler().fit_transform(X)

        kmeans = KMeans(
        n_clusters=k+1,
        n_init=20,
        random_state=SEED
        )
        column_name = f'k-mean-{k}-spars-{rate*10:.0f}'
        df_baja[column_name] = kmeans.fit_predict(X_escalado)
        dfs_baja[(rate, k)] = df_baja.copy()
        labels = kmeans.labels_
        resultados.append({
            'column_name':column_name,
            "sparsity_rate": rate,
            "k_baja": k,
            "clusters_totales": k + 1,
            "tamanios_clusters": pd.Series(labels).value_counts().sort_index().to_dict(),
            "columnas_usadas": X.shape[1],
            "columnas_excluidas_sparse": len(sparse_columns),
            "inercia": kmeans.inertia_,                                                   # menor
            "iteraciones": kmeans.n_iter_,
            "silhouette": silhouette_score(X_escalado, labels),                          # mayor
            "davies_bouldin": davies_bouldin_score(X_escalado, labels),                   # menor
            "calinski_harabasz": calinski_harabasz_score(X_escalado, labels)              # mayor
        })
tabla_resultados = pd.DataFrame(resultados)

tabla_resultados.sort_values(
    "silhouette",
    ascending=False
)

,column_name,sparsity_rate,k_baja,clusters_totales,tamanios_clusters,columnas_usadas,columnas_excluidas_sparse,inercia,iteraciones,silhouette,davies_bouldin,calinski_harabasz
0,k-mean-3-spars-3,0.3,3,4,"{0: 7389, 1: 8, 2: 4463, 3: 367}",47,106,4.653150e+05,24,0.144006,1.970643,850.451709
4,k-mean-3-spars-4,0.4,3,4,"{0: 3520, 1: 5, 2: 831, 3: 7871}",53,100,5.267875e+05,31,0.139017,1.775065,843.166022
5,k-mean-4-spars-4,0.4,4,5,"{0: 3375, 1: 903, 2: 58, 3: 7121, 4: 5}",53,100,4.760372e+05,30,0.129672,1.807245,721.943837
2,k-mean-5-spars-3,0.3,5,6,"{0: 47, 1: 4191, 2: 7, 3: 523, 4: 6231, 5: 5}",47,106,3.920311e+05,35,0.123656,1.757273,640.486640
16,k-mean-3-spars-7,0.7,3,4,"{0: 1338, 1: 7433, 2: 3424, 3: 32}",77,76,7.719902e+05,21,0.119310,2.271560,765.450572
12,k-mean-3-spars-6,0.6,3,4,"{0: 3850, 1: 7613, 2: 4, 3: 760}",68,85,6.740155e+05,47,0.114362,1.897703,803.764522
17,k-mean-4-spars-7,0.7,4,5,"{0: 1157, 1: 3375, 2: 2, 3: 6924, 4: 4}",77,76,7.003009e+05,14,0.112868,1.671769,651.743151
8,k-mean-3-spars-5,0.5,3,4,"{0: 3430, 1: 6404, 2: 2220, 3: 173}",57,96,5.724814e+05,11,0.111468,2.549741,798.744656
18,k-mean-5-spars-7,0.7,5,6,"{0: 68, 1: 3292, 2: 2, 3: 6538, 4: 1100, 5: 4}",77,76,6.459895e+05,32,0.107758,1.665871,610.554162
13,k-mean-4-spars-6,0.6,4,5,"{0: 116, 1: 1640, 2: 3299, 3: 6403, 4: 4}",68,85,6.073532e+05,39,0.107691,2.119350,703.332464
20,k-mean-3-spars-8,0.8,3,4,"{0: 7266, 1: 1508, 2: 3408, 3: 45}",83,70,8.408132e+05,23,0.107597,2.423876,724.791494
7,k-mean-6-spars-4,0.4,6,7,"{0: 3253, 1: 2774, 2: 311, 3: 4195, 4: 131, 5:...",53,100,4.199194e+05,17,0.103143,1.972648,578.683792
21,k-mean-4-spars-8,0.8,4,5,"{0: 3323, 1: 1283, 2: 6780, 3: 74, 4: 2}",83,70,7.617222e+05,14,0.095161,1.928397,626.830058
9,k-mean-4-spars-5,0.5,4,5,"{0: 2772, 1: 49, 2: 3328, 3: 5062, 4: 251}",57,96,5.197744e+05,11,0.094301,2.443263,672.826707
23,k-mean-6-spars-8,0.8,6,7,"{0: 5738, 1: 3190, 2: 73, 3: 1603, 4: 2, 5: 89...",83,70,6.630386e+05,29,0.093231,1.934842,546.879939
14,k-mean-5-spars-6,0.6,5,6,"{0: 3227, 1: 2267, 2: 20, 3: 5246, 4: 239, 5: 5}",68,85,5.625091e+05,70,0.091983,2.182506,640.337348
6,k-mean-5-spars-4,0.4,5,6,"{0: 3091, 1: 3292, 2: 3954, 3: 31, 4: 5, 5: 631}",53,100,4.433221e+05,28,0.091161,2.174153,639.483878
24,k-mean-3-spars-9,0.9,3,4,"{0: 3150, 1: 2204, 2: 6690, 3: 183}",99,54,1.024277e+06,32,0.088106,2.790387,643.372572
11,k-mean-6-spars-5,0.5,6,7,"{0: 61, 1: 2916, 2: 2615, 3: 5, 4: 1131, 5: 38...",57,96,4.563862e+05,33,0.087679,2.177328,557.140321
22,k-mean-5-spars-8,0.8,5,6,"{0: 3070, 1: 2170, 2: 75, 3: 259, 4: 2, 5: 5428}",83,70,7.095077e+05,37,0.085896,2.277557,563.663122
25,k-mean-4-spars-9,0.9,4,5,"{0: 2135, 1: 3045, 2: 260, 3: 6020, 4: 2}",99,54,9.340101e+05,19,0.084781,2.426241,545.256174
19,k-mean-6-spars-7,0.7,6,7,"{0: 503, 1: 2834, 2: 4, 3: 2004, 4: 211, 5: 51...",77,76,6.128634e+05,27,0.080617,1.955746,550.911566
10,k-mean-5-spars-5,0.5,5,6,"{0: 2885, 1: 3780, 2: 105, 3: 1047, 4: 5, 5: 3...",57,96,4.856430e+05,54,0.079018,2.401538,591.434581
15,k-mean-6-spars-6,0.6,6,7,"{0: 2469, 1: 138, 2: 1191, 3: 3770, 4: 3110, 5...",68,85,5.337769e+05,22,0.076207,2.255179,575.135965
26,k-mean-5-spars-9,0.9,5,6,"{0: 5646, 1: 3056, 2: 442, 3: 75, 4: 1783, 5: 2}",99,54,8.722037e+05,49,0.075668,2.359827,492.232980
1,k-mean-4-spars-3,0.3,4,5,"{0: 3434, 1: 2199, 2: 5598, 3: 7, 4: 224}",47,106,4.237013e+05,21,0.075059,2.244613,700.011124
3,k-mean-6-spars-3,0.3,6,7,"{0: 3850, 1: 2987, 2: 73, 3: 2770, 4: 46, 5: 9...",47,106,3.703753e+05,21,0.073464,2.128942,585.643573
27,k-mean-6-spars-9,0.9,6,7,"{0: 5400, 1: 2629, 2: 369, 3: 2, 4: 61, 5: 559...",99,54,8.326972e+05,65,0.060721,2.306698,438.684901

In [87]:
pd.Series(labels).value_counts().sort_index().to_dict()

{0: 5400, 1: 2629, 2: 369, 3: 2, 4: 61, 5: 559, 6: 1678}

In [82]:
df_baja = dfs_baja[(0.3, 3)]
pd.crosstab(
        df_baja["k-mean-3-spars-3"],
        df_baja["ternaria"],
        margins=True
    )

ternaria          BAJA+1  BAJA+2  continua    All
k-mean-3-spars-3
0                   3569    2760      1060   7389
1                      2       1         5      8
2                   1469    1254      1740   4463
3                     63      52       252    367
All                 5103    4067      3057  12227

## Hierarchical

In [ ]:
sparsity_rates = [0.3, .4, .5, .6, .7, .8, .9]
ks = [3, 4, 5, 6]
linkages = ["ward", "complete", "average", "single"]
metrics = ["euclidean", "manhattan", "cosine"]

resultados = []
dfs_baja = {}

for rate in sparsity_rates:
    sparse_columns = []
    non_sparse_columns = []

    for columna in proporcion_ceros.items():
        if columna[1] > rate:
            sparse_columns.append(columna[0])
        else:
            non_sparse_columns.append(columna[0])

    _columnas_excluir = columnas_excluir + [x for x in sparse_columns]

    for k in ks:
        mask_random = get_random_continua(k, mask_baja)
        df_baja = df.loc[mask_baja | mask_random].copy()
        df_baja.fillna(0, inplace=True)

        labels_reales = df_baja["ternaria"]

        X = (
            df_baja
            .drop(columns=_columnas_excluir)
            .select_dtypes(include="number")
        )

        X_escalado = StandardScaler().fit_transform(X)

        for linkage in linkages:
            for metric in metrics:

                # Ward solamente admite distancia euclídea
                if linkage == "ward" and metric != "euclidean":
                    continue

                modelo = AgglomerativeClustering(
                    n_clusters=k + 1,
                    linkage=linkage,
                    metric=metric
                )

                labels = modelo.fit_predict(X_escalado)

                column_name = (
                    f"agg-{k}-{linkage}-{metric}-spars-{rate*10:.0f}"
                )

                df_baja[column_name] = labels

                resultados.append({
                    "column_name": column_name,
                    "sparsity_rate": rate,
                    "k_baja": k,
                    "clusters_totales": k + 1,
                    "linkage": linkage,
                    "metric": metric,
                    "columnas_usadas": X.shape[1],
                    "columnas_excluidas_sparse": len(sparse_columns),
                    "silhouette": silhouette_score(X_escalado, labels),
                    "davies_bouldin": davies_bouldin_score(
                        X_escalado,
                        labels
                    ),
                    "calinski_harabasz": calinski_harabasz_score(
                        X_escalado,
                        labels
                    ),
                    "tamanios_clusters": (
                        pd.Series(labels)
                        .value_counts()
                        .sort_index()
                        .to_dict()
                    )
                })

        dfs_baja[(rate, k)] = df_baja.copy()

tabla_resultados = pd.DataFrame(resultados)

In [ ]:
#Guardamos resultados
# tabla_resultados.to_csv(os.path.join(os.getcwd(), 'clus_hier_sparse.csv' ))

In [111]:
tabla_resultados.sort_values(by='silhouette', ascending=False).iloc[155:175]

,column_name,sparsity_rate,k_baja,clusters_totales,linkage,metric,columnas_usadas,columnas_excluidas_sparse,silhouette,davies_bouldin,calinski_harabasz,tamanios_clusters
92,agg-4-complete-manhattan-spars-5,0.5,4,5,complete,manhattan,57,96,0.728739,1.027458,284.602129,"{0: 11393, 1: 65, 2: 1, 3: 1, 4: 2}"
112,agg-6-complete-manhattan-spars-5,0.5,6,7,complete,manhattan,57,96,0.721408,0.857263,271.544332,"{0: 10648, 1: 12, 2: 3, 3: 2, 4: 24, 5: 1, 6: 8}"
192,agg-6-complete-manhattan-spars-7,0.7,6,7,complete,manhattan,77,76,0.721055,1.047652,300.885112,"{0: 10635, 1: 12, 2: 32, 3: 3, 4: 2, 5: 1, 6: 13}"
232,agg-6-complete-manhattan-spars-8,0.8,6,7,complete,manhattan,83,70,0.715611,1.233796,272.832435,"{0: 10631, 1: 46, 2: 13, 3: 3, 4: 2, 5: 1, 6: 2}"
262,agg-5-complete-manhattan-spars-9,0.9,5,6,complete,manhattan,99,54,0.678950,1.388425,275.414828,"{0: 53, 1: 2, 2: 53, 3: 3, 4: 10892, 5: 1}"
72,agg-6-complete-manhattan-spars-4,0.4,6,7,complete,manhattan,53,100,0.649275,0.852970,235.046634,"{0: 10648, 1: 7, 2: 31, 3: 2, 4: 1, 5: 1, 6: 8}"
142,agg-5-complete-manhattan-spars-6,0.6,5,6,complete,manhattan,68,85,0.616629,1.051805,318.391674,"{0: 10913, 1: 13, 2: 71, 3: 4, 4: 2, 5: 1}"
62,agg-5-complete-manhattan-spars-4,0.4,5,6,complete,manhattan,53,100,0.515659,1.275989,291.223365,"{0: 359, 1: 7, 2: 10610, 3: 26, 4: 1, 5: 1}"
22,agg-5-complete-manhattan-spars-3,0.3,5,6,complete,manhattan,47,106,0.508618,0.868048,315.945207,"{0: 10806, 1: 184, 2: 2, 3: 2, 4: 9, 5: 1}"
12,agg-4-complete-manhattan-spars-3,0.3,4,5,complete,manhattan,47,106,0.491187,1.133248,384.620609,"{0: 276, 1: 8, 2: 1, 3: 11168, 4: 9}"
182,agg-5-complete-manhattan-spars-7,0.7,5,6,complete,manhattan,77,76,0.477454,1.163211,367.002429,"{0: 10603, 1: 383, 2: 11, 3: 4, 4: 2, 5: 1}"
249,agg-3-single-cosine-spars-9,0.9,3,4,single,cosine,99,54,0.402043,0.617328,10.000189,"{0: 12222, 1: 1, 2: 3, 3: 1}"
102,agg-5-complete-manhattan-spars-5,0.5,5,6,complete,manhattan,57,96,0.131125,1.598678,326.191819,"{0: 2937, 1: 8, 2: 8030, 3: 2, 4: 26, 5: 1}"
160,agg-3-ward-euclidean-spars-7,0.7,3,4,ward,euclidean,77,76,0.118039,2.043632,631.497518,"{0: 3467, 1: 835, 2: 7922, 3: 3}"
40,agg-3-ward-euclidean-spars-4,0.4,3,4,ward,euclidean,53,100,0.112137,2.146793,709.385591,"{0: 701, 1: 4129, 2: 7387, 3: 10}"
70,agg-6-ward-euclidean-spars-4,0.4,6,7,ward,euclidean,53,100,0.111159,1.960753,501.705201,"{0: 3936, 1: 95, 2: 6220, 3: 8, 4: 52, 5: 5, 6..."
60,agg-5-ward-euclidean-spars-4,0.4,5,6,ward,euclidean,53,100,0.109822,2.095045,548.666876,"{0: 48, 1: 139, 2: 6187, 3: 3406, 4: 4, 5: 1220}"
30,agg-6-ward-euclidean-spars-3,0.3,6,7,ward,euclidean,47,106,0.109789,1.853656,493.489128,"{0: 741, 1: 3135, 2: 48, 3: 6633, 4: 5, 5: 8, ..."
100,agg-5-ward-euclidean-spars-5,0.5,5,6,ward,euclidean,57,96,0.105291,2.087655,501.358428,"{0: 3, 1: 394, 2: 6394, 3: 4, 4: 4110, 5: 99}"
3,agg-3-complete-cosine-spars-3,0.3,3,4,complete,cosine,47,106,0.103259,3.586792,433.137656,"{0: 7150, 1: 2118, 2: 1581, 3: 1378}"

In [112]:
df_baja = dfs_baja[(0.5, 5)]
pd.crosstab(
        df_baja["agg-5-complete-manhattan-spars-5"],
        df_baja["ternaria"],
        margins=True
    )
# df_baja

ternaria                          BAJA+1  BAJA+2  continua    All
agg-5-complete-manhattan-spars-5
0                                   1156     909       872   2937
1                                      4       2         2      8
2                                   3934    3148       948   8030
3                                      1       1         0      2
4                                      8       7        11     26
5                                      0       0         1      1
All                                 5103    4067      1834  11004