# Evaluación multisemilla por ganancia de los mejores modelos de z495

Esta notebook:

1. carga el dataset crudo y genera `clase_ternaria`;
2. lee un `BO_log.txt` generado por R o por Optuna/Python;
3. selecciona los mejores `n` conjuntos de hiperparámetros;
4. entrena cada conjunto con `m` semillas distintas sobre todos los datos de entrenamiento;
5. calcula y promedia la ganancia sobre el período futuro, como en Producción de z494.

No ejecuta una nueva optimización bayesiana.

## Librerías

Si falta algún paquete, instalarlo previamente en el entorno de R correspondiente.

In [16]:
library(data.table)
library(here)
library(primes)
library(lightgbm)

options(scipen = 999)

## Configuración

`experimento_origen` puede ser el nombre de una carpeta dentro de `DATA/EXP` o una ruta completa.

In [17]:
root <- here()
dataset_folder <- file.path(root, "DATA", "DATASETS")
exp_folder <- file.path(root, "DATA", "EXP")

PARAM <- list()
PARAM$experimento_origen <- "PY495-02"
PARAM$archivo_resultados <- "BO_log.txt"

PARAM$semilla_primigenia <- 230047
PARAM$n_mejores <- 1L
PARAM$m_semillas <- 5L

PARAM$train_final <- c(202104)
PARAM$future <- c(202106)
PARAM$semilla_kaggle <- 314159
PARAM$cortes <- seq(4000, 19000, by = 500)
PARAM$trainingstrategy$undersampling <- 0.1

In [18]:
# Parámetros fijos de z495. Los presentes en BO_log.txt los pisan.
PARAM$lgbm$param_fijos <- list(
  boosting = "gbdt",
  objective = "binary",
  metric = "average_precision",
  feature_pre_filter = FALSE,
  first_metric_only = FALSE,
  boost_from_average = TRUE,
  force_row_wise = TRUE,
  deterministic = TRUE,
  verbosity = -100,

  seed = PARAM$semilla_primigenia,

  max_depth = -1L,
  min_gain_to_split = 0,
  lambda_l1 = 0.0,
  lambda_l2 = 0.0,
  max_bin = 31L,

  bagging_fraction = 1.0,
  pos_bagging_fraction = 1.0,
  neg_bagging_fraction = 1.0,
  is_unbalance = FALSE,
  scale_pos_weight = 1.0,

  drop_rate = 0.1,
  max_drop = 50L,
  skip_drop = 0.5,
  extra_trees = FALSE,

  early_stopping = 0L,
  min_data_in_leaf = 0L,
  feature_fraction = 0.50,
  learning_rate = 0.005,

  num_iterations = 20000L,
  num_leaves = 1024L,
  min_sum_hessian_in_leaf = 1e-6
)

## Dataset y clase ternaria

Se conserva la lógica de generación utilizada en z495.

In [19]:
dataset_url <- file.path(dataset_folder, "competencia_01_crudo.csv")

if (!file.exists(dataset_url)) {
  stop("No existe el dataset: ", dataset_url)
}

dataset <- fread(dataset_url)

dsimple <- dataset[, .(
  pos = .I,
  numero_de_cliente,
  periodo0 = as.integer(foto_mes / 100) * 12 + foto_mes %% 100
)]

setorder(dsimple, numero_de_cliente, periodo0)

periodo_ultimo <- dsimple[, max(periodo0)]
periodo_anteultimo <- periodo_ultimo - 1L

dsimple[, c("periodo1", "periodo2") :=
  shift(periodo0, n = 1:2, fill = NA, type = "lead"),
  by = numero_de_cliente
]

dsimple[periodo0 < periodo_anteultimo, clase_ternaria := "CONTINUA"]

dsimple[
  periodo0 < periodo_ultimo &
    (is.na(periodo1) | periodo0 + 1L < periodo1),
  clase_ternaria := "BAJA+1"
]

dsimple[
  periodo0 < periodo_anteultimo & periodo0 + 1L == periodo1 &
    (is.na(periodo2) | periodo0 + 2L < periodo2),
  clase_ternaria := "BAJA+2"
]

setorder(dsimple, pos)
dataset[, clase_ternaria := dsimple$clase_ternaria]

setorder(dataset, foto_mes, clase_ternaria, numero_de_cliente)
dataset[, .N, by = .(foto_mes, clase_ternaria)]

   foto_mes clase_ternaria N
1  202103   BAJA+1           1019
2  202103   BAJA+2            960
3  202103   CONTINUA       160921
4  202104   BAJA+1            964
5  202104   BAJA+2           1139
6  202104   CONTINUA       161181
7  202105   BAJA+1           1143
8  202105   BAJA+2            870
9  202105   CONTINUA       161755
10 202106   BAJA+1            874
11 202106   BAJA+2           1098
12 202106   CONTINUA       162142
13 202107   NA             163245
14 202107   BAJA+1           1103
15 202108   NA             164647

In [20]:
dataset[, clase01 := fifelse(
  clase_ternaria %in% c("BAJA+2", "BAJA+1"),
  1L,
  0L
)]

dataset_train <- copy(dataset[foto_mes %in% PARAM$train_final])
dfuture <- copy(dataset[foto_mes %in% PARAM$future])

campos_buenos <- setdiff(
  names(dataset_train),
  c(
    "clase_ternaria", "clase01", "fold", "azar", "training",
    "cprestamos_personales", "mprestamos_personales"
  )
)

dtrain_final <- lgb.Dataset(
  data = data.matrix(dataset_train[, ..campos_buenos]),
  label = dataset_train[, clase01]
)

dataset_train[, .N, by = clase_ternaria]

  clase_ternaria N
1 BAJA+1            964
2 BAJA+2           1139
3 CONTINUA       161181

## Lectura de resultados de R o Python

La función reconoce:

- `metrica` en el log de z495/R;
- `value` y columnas `params_*` en el log de Optuna/Python;
- `y` en otros logs de R compatibles.

In [21]:
resolver_carpeta_experimento <- function(experimento) {
  if (dir.exists(experimento)) {
    return(normalizePath(experimento, mustWork = TRUE))
  }

  candidato <- file.path(exp_folder, experimento)
  if (!dir.exists(candidato)) {
    stop("No existe la carpeta del experimento: ", candidato)
  }

  normalizePath(candidato, mustWork = TRUE)
}


leer_mejores_resultados <- function(carpeta, archivo, n_mejores) {
  ruta <- file.path(carpeta, archivo)
  if (!file.exists(ruta)) {
    stop("No existe el archivo de resultados: ", ruta)
  }

  tb <- fread(ruta)
  tb[, fila_origen := .I]

  if ("state" %in% names(tb)) {
    tb <- tb[state == "COMPLETE"]
  }

  # Optuna escribe los hiperparámetros como params_nombre.
  columnas_python <- grep("^params_", names(tb), value = TRUE)
  for (columna in columnas_python) {
    nombre_lgbm <- sub("^params_", "", columna)
    if (!nombre_lgbm %in% names(tb)) {
      setnames(tb, columna, nombre_lgbm)
    }
  }

  candidatas_metrica <- c("metrica", "value", "y")
  campo_metrica <- candidatas_metrica[candidatas_metrica %in% names(tb)][1]

  if (is.na(campo_metrica)) {
    stop("No se encontró una columna de métrica: metrica, value o y")
  }

  tb[, metrica_origen := as.numeric(get(campo_metrica))]
  tb <- tb[is.finite(metrica_origen)]

  if (nrow(tb) == 0L) {
    stop("El archivo no contiene evaluaciones completas con una métrica válida")
  }

  setorder(tb, -metrica_origen)
  tb <- head(tb, min(as.integer(n_mejores), nrow(tb)))
  tb[, ranking_origen := .I]

  if ("iter" %in% names(tb)) {
    tb[, id_origen := as.character(iter)]
  } else if ("number" %in% names(tb)) {
    tb[, id_origen := as.character(number)]
  } else {
    tb[, id_origen := as.character(fila_origen)]
  }

  tb[]
}

In [22]:
carpeta_experimento <- resolver_carpeta_experimento(
  PARAM$experimento_origen
)

mejores_modelos <- leer_mejores_resultados(
  carpeta = carpeta_experimento,
  archivo = PARAM$archivo_resultados,
  n_mejores = PARAM$n_mejores
)

columnas_parametros <- intersect(
  names(PARAM$lgbm$param_fijos),
  names(mejores_modelos)
)

columnas_mostrar <- unique(c(
  "ranking_origen", "id_origen", "metrica_origen",
  columnas_parametros
))

mejores_modelos[, ..columnas_mostrar]

  ranking_origen id_origen metrica_origen learning_rate num_iterations
1 1              5         0.1182831      0.003697844   2780
  num_leaves min_sum_hessian_in_leaf
1 24         0.06401048

## Semillas

Se generan semillas primas reproducibles y se utiliza `L'Ecuyer-CMRG`, siguiendo el manejo de semillas de las notebooks en R.

In [23]:
primos <- generate_primes(100000, 1000000)

if (PARAM$m_semillas > length(primos)) {
  stop("m_semillas supera la cantidad de números primos disponibles")
}

set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
PARAM$semillas <- sample(
  primos,
  size = PARAM$m_semillas,
  replace = FALSE
)

PARAM$semillas

[1] 150497 931363 240707 993683 121349

## Ganancia de Producción de z494

Se conserva la división fija `Public`/`Private` de z494. La semilla Kaggle es independiente de las semillas usadas para entrenar los modelos.

In [24]:
particionar <- function(
  data,
  division,
  agrupa = "",
  campo = "fold",
  start = 1L,
  seed = NA
) {
  if (!is.na(seed)) {
    set.seed(seed, kind = "L'Ecuyer-CMRG")
  }

  bloque <- unlist(mapply(
    function(x, y) rep(y, x),
    division,
    seq(from = start, length.out = length(division))
  ))

  data[, (campo) := sample(
    rep(bloque, ceiling(.N / length(bloque)))
  )[1:.N], by = agrupa]
}


realidad_inicializar <- function(pfuture, pparam) {
  drealidad <- pfuture[, .(
    numero_de_cliente,
    foto_mes,
    clase_ternaria
  )]

  particionar(
    data = drealidad,
    division = c(3L, 7L),
    agrupa = "clase_ternaria",
    seed = pparam$semilla_kaggle
  )

  drealidad
}


realidad_evaluar <- function(prealidad, pprediccion) {
  prealidad[
    pprediccion,
    on = c("numero_de_cliente", "foto_mes"),
    predicted := i.Predicted
  ]

  tbl <- prealidad[, .(
    qty = .N
  ), by = .(fold, predicted, clase_ternaria)]

  res <- list(
    public = tbl[
      fold == 1L & predicted == 1L,
      sum(qty * fifelse(clase_ternaria == "BAJA+2", 1072500, -27500))
    ] / 0.3,
    private = tbl[
      fold == 2L & predicted == 1L,
      sum(qty * fifelse(clase_ternaria == "BAJA+2", 1072500, -27500))
    ] / 0.7,
    total = tbl[
      predicted == 1L,
      sum(qty * fifelse(clase_ternaria == "BAJA+2", 1072500, -27500))
    ]
  )

  prealidad[, predicted := NULL]
  res
}


drealidad <- realidad_inicializar(dfuture, PARAM)

## Entrenamiento y evaluación de los mejores modelos

Cada fila del log pisa los parámetros fijos correspondientes. Cada semilla cambia el entrenamiento de LightGBM, pero no los hiperparámetros del experimento.

In [25]:
extraer_parametros_modelo <- function(fila_modelo, semilla) {
  disponibles <- intersect(
    names(PARAM$lgbm$param_fijos),
    names(fila_modelo)
  )

  parametros_log <- as.list(fila_modelo[, ..disponibles])
  parametros_log <- parametros_log[vapply(
    parametros_log,
    function(valor) length(valor) == 1L && !is.na(valor),
    logical(1)
  )]

  parametros <- modifyList(
    PARAM$lgbm$param_fijos,
    parametros_log
  )

  parametros$seed <- as.integer(semilla)

  parametros_enteros <- intersect(
    c(
      "num_iterations", "num_leaves", "max_depth", "max_bin",
      "max_drop", "early_stopping", "min_data_in_leaf"
    ),
    names(parametros)
  )

  parametros[parametros_enteros] <- lapply(
    parametros[parametros_enteros],
    as.integer
  )

  # Normalización de Producción de z494. En z495 permanece en cero.
  parametros$min_data_in_leaf <- round(
    parametros$min_data_in_leaf /
      PARAM$trainingstrategy$undersampling
  )

  parametros
}


entrenar_y_predecir <- function(fila_modelo, semilla) {
  parametros <- extraer_parametros_modelo(fila_modelo, semilla)

  modelo <- lgb.train(
    data = dtrain_final,
    param = parametros
  )

  prediccion <- predict(
    modelo,
    data.matrix(dfuture[, ..campos_buenos])
  )

  rm(modelo)

  prediccion
}

In [26]:
resultados <- vector(
  mode = "list",
  length = nrow(mejores_modelos) *
    length(PARAM$semillas) *
    length(PARAM$cortes)
)

k <- 0L

for (modelo_id in seq_len(nrow(mejores_modelos))) {
  cat('nuevo modelo')
  flush.console()
  fila_modelo <- mejores_modelos[modelo_id]

  for (semilla in PARAM$semillas) {
    cat('nueva semilla')
    flush.console()
    prediccion <- entrenar_y_predecir(
      fila_modelo = fila_modelo,
      semilla = semilla
    )

    tb_prediccion <- dfuture[, .(
      numero_de_cliente,
      foto_mes,
      clase_ternaria
    )]

    tb_prediccion[, prob := prediccion]
    setorder(tb_prediccion, -prob)

    for (envios in PARAM$cortes) {
      k <- k + 1L

      tb_prediccion[, Predicted := 0L]
      tb_prediccion[seq_len(envios), Predicted := 1L]

      ganancia <- realidad_evaluar(
        prealidad = drealidad,
        pprediccion = tb_prediccion
      )

      resultados[[k]] <- data.table(
        modelo_id = modelo_id,
        ranking_origen = fila_modelo$ranking_origen,
        id_origen = fila_modelo$id_origen,
        metrica_origen = fila_modelo$metrica_origen,
        semilla = as.integer(semilla),
        envios = as.integer(envios),
        ganancia_total = ganancia$total,
        ganancia_public_estimada = ganancia$public,
        ganancia_private_estimada = ganancia$private
      )

      cat(
        "Modelo=", modelo_id,
        " Semilla=", semilla,
        " Envios=", envios,
        " TOTAL=", ganancia$total,
        " Public=", ganancia$public,
        " Private=", ganancia$private,
        "\n",
        sep = ""
      )
    }

    rm(prediccion, tb_prediccion)
    gc(full = TRUE, verbose = FALSE)
  }
}

resultados_detalle <- rbindlist(resultados)
resultados_detalle[]

Modelo=1 Semilla=150497 Envios=4000 TOTAL=315700000 Public=312583333 Private=317035714
Modelo=1 Semilla=150497 Envios=4500 TOTAL=336050000 Public=350441667 Private=329882143
Modelo=1 Semilla=150497 Envios=5000 TOTAL=349800000 Public=367858333 Private=342060714
Modelo=1 Semilla=150497 Envios=5500 TOTAL=355850000 Public=373083333 Private=348464286
Modelo=1 Semilla=150497 Envios=6000 TOTAL=366300000 Public=374458333 Private=362803571
Modelo=1 Semilla=150497 Envios=6500 TOTAL=376750000 Public=387750000 Private=372035714
Modelo=1 Semilla=150497 Envios=7000 TOTAL=392700000 Public=395908333 Private=391325000
Modelo=1 Semilla=150497 Envios=7500 TOTAL=399850000 Public=417450000 Private=392307143
Modelo=1 Semilla=150497 Envios=8000 TOTAL=405900000 Public=433583333 Private=394035714
Modelo=1 Semilla=150497 Envios=8500 TOTAL=414150000 Public=445316667 Private=400792857
Modelo=1 Semilla=150497 Envios=9000 TOTAL=418000000 Public=456225000 Private=401617857
Modelo=1 Semilla=150497 Envios=9500 TOTAL=420750000 Public=456591667 Private=405389286
Modelo=1 Semilla=150497 Envios=10000 TOTAL=427900000 Public=471441667 Private=409239286
Modelo=1 Semilla=150497 Envios=10500 TOTAL=438350000 Public=465391667 Private=426760714
Modelo=1 Semilla=150497 Envios=11000 TOTAL=442200000 Public=477766667 Private=426957143
Modelo=1 Semilla=150497 Envios=11500 TOTAL=441650000 Public=474741667 Private=427467857
Modelo=1 Semilla=150497 Envios=12000 TOTAL=446600000 Public=471441667 Private=435953571
Modelo=1 Semilla=150497 Envios=12500 TOTAL=447150000 Public=471625000 Private=436660714
Modelo=1 Semilla=150497 Envios=13000 TOTAL=438900000 Public=464750000 Private=427821429
Modelo=1 Semilla=150497 Envios=13500 TOTAL=433950000 Public=458608333 Private=423382143
Modelo=1 Semilla=150497 Envios=14000 TOTAL=435600000 Public=453750000 Private=427821429
Modelo=1 Semilla=150497 Envios=14500 TOTAL=439450000 Public=453750000 Private=433321429
Modelo=1 Semilla=150497 Envios=15000 TOTAL=434500000 Public=443941667 Private=430453571
Modelo=1 Semilla=150497 Envios=15500 TOTAL=427350000 Public=445500000 Private=419571429
Modelo=1 Semilla=150497 Envios=16000 TOTAL=425700000 Public=442016667 Private=418707143
Modelo=1 Semilla=150497 Envios=16500 TOTAL=421850000 Public=432391667 Private=417332143
Modelo=1 Semilla=150497 Envios=17000 TOTAL=412500000 Public=421025000 Private=408846429
Modelo=1 Semilla=150497 Envios=17500 TOTAL=406450000 Public=412133333 Private=404014286
Modelo=1 Semilla=150497 Envios=18000 TOTAL=404800000 Public=409383333 Private=402835714
Modelo=1 Semilla=150497 Envios=18500 TOTAL=396550000 Public=396000000 Private=396785714
Modelo=1 Semilla=150497 Envios=19000 TOTAL=394900000 Public=397283333 Private=393878571
Modelo=1 Semilla=931363 Envios=4000 TOTAL=322300000 Public=313316667 Private=326150000
Modelo=1 Semilla=931363 Envios=4500 TOTAL=340450000 Public=339625000 Private=340803571
Modelo=1 Semilla=931363 Envios=5000 TOTAL=350900000 Public=357683333 Private=347992857
Modelo=1 Semilla=931363 Envios=5500 TOTAL=363550000 Public=370241667 Private=360682143
Modelo=1 Semilla=931363 Envios=6000 TOTAL=376200000 Public=379316667 Private=374864286
Modelo=1 Semilla=931363 Envios=6500 TOTAL=382250000 Public=380325000 Private=383075000
Modelo=1 Semilla=931363 Envios=7000 TOTAL=389400000 Public=390683333 Private=388850000
Modelo=1 Semilla=931363 Envios=7500 TOTAL=393250000 Public=412958333 Private=384803571
Modelo=1 Semilla=931363 Envios=8000 TOTAL=405900000 Public=436425000 Private=392817857
Modelo=1 Semilla=931363 Envios=8500 TOTAL=416350000 Public=452100000 Private=401028571
Modelo=1 Semilla=931363 Envios=9000 TOTAL=416900000 Public=454850000 Private=400635714
Modelo=1 Semilla=931363 Envios=9500 TOTAL=426250000 Public=455125000 Private=413875000
Modelo=1 Semilla=931363 Envios=10000 TOTAL=427900000 Public=455308333 Private=416153571
Modelo=1 Semilla=931363 Envios=10500 TOTAL=432850000 Public=462733333 Private=420042857
Modelo=1 Semilla=931363 Envios=11000 TOTAL=437800000 Public=473641667 Private=422439286
Modelo=1 Semilla=931363 Envios=11500 TOTAL=443850000 Public=485375000 Private=426053571
Modelo=1 Semilla=931363 Envios=12000 TOTAL=445500000 Public=479600000 Private=430885714
Modelo=1 Semilla=931363 Envios=12500 TOTAL=446050000 Public=471625000 Private=435089286
Modelo=1 Semilla=931363 Envios=13000 TOTAL=441100000 Public=460808333 Private=432653571
Modelo=1 Semilla=931363 Envios=13500 TOTAL=441650000 Public=457875000 Private=434696429
Modelo=1 Semilla=931363 Envios=14000 TOTAL=441100000 Public=455491667 Private=434932143
Modelo=1 Semilla=931363 Envios=14500 TOTAL=439450000 Public=456133333 Private=432300000
Modelo=1 Semilla=931363 Envios=15000 TOTAL=436700000 Public=450083333 Private=430964286
Modelo=1 Semilla=931363 Envios=15500 TOTAL=427350000 Public=436058333 Private=423617857
Modelo=1 Semilla=931363 Envios=16000 TOTAL=421300000 Public=429550000 Private=417764286
Modelo=1 Semilla=931363 Envios=16500 TOTAL=415250000 Public=433308333 Private=407510714
Modelo=1 Semilla=931363 Envios=17000 TOTAL=408100000 Public=422950000 Private=401735714
Modelo=1 Semilla=931363 Envios=17500 TOTAL=403150000 Public=416716667 Private=397335714
Modelo=1 Semilla=931363 Envios=18000 TOTAL=397100000 Public=407641667 Private=392582143
Modelo=1 Semilla=931363 Envios=18500 TOTAL=394350000 Public=400491667 Private=391717857
Modelo=1 Semilla=931363 Envios=19000 TOTAL=387200000 Public=393250000 Private=384607143
Modelo=1 Semilla=240707 Envios=4000 TOTAL=311300000 Public=308825000 Private=312360714
Modelo=1 Semilla=240707 Envios=4500 TOTAL=337150000 Public=339441667 Private=336167857
Modelo=1 Semilla=240707 Envios=5000 TOTAL=345400000 Public=362633333 Private=338014286
Modelo=1 Semilla=240707 Envios=5500 TOTAL=354750000 Public=374183333 Private=346421429
Modelo=1 Semilla=240707 Envios=6000 TOTAL=370700000 Public=379316667 Private=367007143
Modelo=1 Semilla=240707 Envios=6500 TOTAL=385550000 Public=395450000 Private=381307143
Modelo=1 Semilla=240707 Envios=7000 TOTAL=388300000 Public=408741667 Private=379539286
Modelo=1 Semilla=240707 Envios=7500 TOTAL=402050000 Public=421025000 Private=393917857
Modelo=1 Semilla=240707 Envios=8000 TOTAL=408100000 Public=439725000 Private=394546429
Modelo=1 Semilla=240707 Envios=8500 TOTAL=407550000 Public=432941667 Private=396667857
Modelo=1 Semilla=240707 Envios=9000 TOTAL=420200000 Public=452100000 Private=406528571
Modelo=1 Semilla=240707 Envios=9500 TOTAL=424050000 Public=455400000 Private=410614286
Modelo=1 Semilla=240707 Envios=10000 TOTAL=433400000 Public=462458333 Private=420946429
Modelo=1 Semilla=240707 Envios=10500 TOTAL=433950000 Public=471808333 Private=417725000
Modelo=1 Semilla=240707 Envios=11000 TOTAL=437800000 Public=478958333 Private=420160714
Modelo=1 Semilla=240707 Envios=11500 TOTAL=436150000 Public=480700000 Private=417057143
Modelo=1 Semilla=240707 Envios=12000 TOTAL=435600000 Public=474925000 Private=418746429
Modelo=1 Semilla=240707 Envios=12500 TOTAL=436150000 Public=465391667 Private=423617857
Modelo=1 Semilla=240707 Envios=13000 TOTAL=437800000 Public=463650000 Private=426721429
Modelo=1 Semilla=240707 Envios=13500 TOTAL=437250000 Public=458241667 Private=428253571
Modelo=1 Semilla=240707 Envios=14000 TOTAL=441100000 Public=454025000 Private=435560714
Modelo=1 Semilla=240707 Envios=14500 TOTAL=440550000 Public=452375000 Private=435482143
Modelo=1 Semilla=240707 Envios=15000 TOTAL=435600000 Public=457325000 Private=426289286
Modelo=1 Semilla=240707 Envios=15500 TOTAL=428450000 Public=446691667 Private=420632143
Modelo=1 Semilla=240707 Envios=16000 TOTAL=423500000 Public=436425000 Private=417960714
Modelo=1 Semilla=240707 Envios=16500 TOTAL=420750000 Public=429275000 Private=417096429
Modelo=1 Semilla=240707 Envios=17000 TOTAL=415800000 Public=422400000 Private=412971429
Modelo=1 Semilla=240707 Envios=17500 TOTAL=408650000 Public=419925000 Private=403817857
Modelo=1 Semilla=240707 Envios=18000 TOTAL=402600000 Public=410391667 Private=399260714
Modelo=1 Semilla=240707 Envios=18500 TOTAL=395450000 Public=399666667 Private=393642857
Modelo=1 Semilla=240707 Envios=19000 TOTAL=389400000 Public=392516667 Private=388064286
Modelo=1 Semilla=993683 Envios=4000 TOTAL=319000000 Public=313133333 Private=321514286
Modelo=1 Semilla=993683 Envios=4500 TOTAL=338250000 Public=332933333 Private=340528571
Modelo=1 Semilla=993683 Envios=5000 TOTAL=352000000 Public=355300000 Private=350585714
Modelo=1 Semilla=993683 Envios=5500 TOTAL=352550000 Public=366391667 Private=346617857
Modelo=1 Semilla=993683 Envios=6000 TOTAL=365200000 Public=378675000 Private=359425000
Modelo=1 Semilla=993683 Envios=6500 TOTAL=384450000 Public=391141667 Private=381582143
Modelo=1 Semilla=993683 Envios=7000 TOTAL=388300000 Public=397558333 Private=384332143
Modelo=1 Semilla=993683 Envios=7500 TOTAL=399850000 Public=428083333 Private=387750000
Modelo=1 Semilla=993683 Envios=8000 TOTAL=405900000 Public=429825000 Private=395646429
Modelo=1 Semilla=993683 Envios=8500 TOTAL=411950000 Public=440825000 Private=399575000
Modelo=1 Semilla=993683 Envios=9000 TOTAL=414700000 Public=439083333 Private=404250000
Modelo=1 Semilla=993683 Envios=9500 TOTAL=424050000 Public=456225000 Private=410260714
Modelo=1 Semilla=993683 Envios=10000 TOTAL=431200000 Public=463650000 Private=417292857
Modelo=1 Semilla=993683 Envios=10500 TOTAL=433950000 Public=466675000 Private=419925000
Modelo=1 Semilla=993683 Envios=11000 TOTAL=435600000 Public=470433333 Private=420671429
Modelo=1 Semilla=993683 Envios=11500 TOTAL=439450000 Public=481616667 Private=421378571
Modelo=1 Semilla=993683 Envios=12000 TOTAL=442200000 Public=486016667 Private=423421429
Modelo=1 Semilla=993683 Envios=12500 TOTAL=446050000 Public=486200000 Private=428842857
Modelo=1 Semilla=993683 Envios=13000 TOTAL=443300000 Public=473275000 Private=430453571
Modelo=1 Semilla=993683 Envios=13500 TOTAL=436150000 Public=459525000 Private=426132143
Modelo=1 Semilla=993683 Envios=14000 TOTAL=437800000 Public=453383333 Private=431121429
Modelo=1 Semilla=993683 Envios=14500 TOTAL=437250000 Public=454208333 Private=429982143
Modelo=1 Semilla=993683 Envios=15000 TOTAL=434500000 Public=453291667 Private=426446429
Modelo=1 Semilla=993683 Envios=15500 TOTAL=431750000 Public=453841667 Private=422282143
Modelo=1 Semilla=993683 Envios=16000 TOTAL=425700000 Public=443666667 Private=418000000
Modelo=1 Semilla=993683 Envios=16500 TOTAL=421850000 Public=433950000 Private=416664286
Modelo=1 Semilla=993683 Envios=17000 TOTAL=413600000 Public=423591667 Private=409317857
Modelo=1 Semilla=993683 Envios=17500 TOTAL=407550000 Public=420658333 Private=401932143
Modelo=1 Semilla=993683 Envios=18000 TOTAL=399300000 Public=409200000 Private=395057143
Modelo=1 Semilla=993683 Envios=18500 TOTAL=392150000 Public=397191667 Private=389989286
Modelo=1 Semilla=993683 Envios=19000 TOTAL=390500000 Public=390500000 Private=390500000
Modelo=1 Semilla=121349 Envios=4000 TOTAL=315700000 Public=309191667 Private=318489286
Modelo=1 Semilla=121349 Envios=4500 TOTAL=340450000 Public=347325000 Private=337503571
Modelo=1 Semilla=121349 Envios=5000 TOTAL=346500000 Public=355300000 Private=342728571
Modelo=1 Semilla=121349 Envios=5500 TOTAL=360250000 Public=373725000 Private=354475000
Modelo=1 Semilla=121349 Envios=6000 TOTAL=367400000 Public=381700000 Private=361271429
Modelo=1 Semilla=121349 Envios=6500 TOTAL=385550000 Public=398200000 Private=380128571
Modelo=1 Semilla=121349 Envios=7000 TOTAL=394900000 Public=401500000 Private=392071429
Modelo=1 Semilla=121349 Envios=7500 TOTAL=398750000 Public=414516667 Private=391992857
Modelo=1 Semilla=121349 Envios=8000 TOTAL=405900000 Public=428175000 Private=396353571
Modelo=1 Semilla=121349 Envios=8500 TOTAL=411950000 Public=442475000 Private=398867857
Modelo=1 Semilla=121349 Envios=9000 TOTAL=421300000 Public=454208333 Private=407196429
Modelo=1 Semilla=121349 Envios=9500 TOTAL=422950000 Public=457875000 Private=407982143
Modelo=1 Semilla=121349 Envios=10000 TOTAL=424600000 Public=453658333 Private=412146429
Modelo=1 Semilla=121349 Envios=10500 TOTAL=441650000 Public=476300000 Private=426800000
Modelo=1 Semilla=121349 Envios=11000 TOTAL=440000000 Public=483083333 Private=421535714
Modelo=1 Semilla=121349 Envios=11500 TOTAL=444950000 Public=484183333 Private=428135714
Modelo=1 Semilla=121349 Envios=12000 TOTAL=442200000 Public=478225000 Private=426760714
Modelo=1 Semilla=121349 Envios=12500 TOTAL=437250000 Public=471533333 Private=422557143
Modelo=1 Semilla=121349 Envios=13000 TOTAL=436700000 Public=460441667 Private=426525000
Modelo=1 Semilla=121349 Envios=13500 TOTAL=438350000 Public=450816667 Private=433007143
Modelo=1 Semilla=121349 Envios=14000 TOTAL=438900000 Public=455308333 Private=431867857
Modelo=1 Semilla=121349 Envios=14500 TOTAL=437250000 Public=452650000 Private=430650000
Modelo=1 Semilla=121349 Envios=15000 TOTAL=432300000 Public=445775000 Private=426525000
Modelo=1 Semilla=121349 Envios=15500 TOTAL=430650000 Public=446325000 Private=423932143
Modelo=1 Semilla=121349 Envios=16000 TOTAL=420200000 Public=438350000 Private=412421429
Modelo=1 Semilla=121349 Envios=16500 TOTAL=417450000 Public=433400000 Private=410614286
Modelo=1 Semilla=121349 Envios=17000 TOTAL=415800000 Public=422675000 Private=412853571
Modelo=1 Semilla=121349 Envios=17500 TOTAL=408650000 Public=416808333 Private=405153571
Modelo=1 Semilla=121349 Envios=18000 TOTAL=402600000 Public=405533333 Private=401342857
Modelo=1 Semilla=121349 Envios=18500 TOTAL=394350000 Public=395175000 Private=393996429
Modelo=1 Semilla=121349 Envios=19000 TOTAL=394900000 Public=389125000 Private=397375000

    modelo_id ranking_origen id_origen metrica_origen semilla envios
1   1         1              5         0.1182831      150497   4000
2   1         1              5         0.1182831      150497   4500
3   1         1              5         0.1182831      150497   5000
4   1         1              5         0.1182831      150497   5500
5   1         1              5         0.1182831      150497   6000
6   1         1              5         0.1182831      150497   6500
7   1         1              5         0.1182831      150497   7000
8   1         1              5         0.1182831      150497   7500
9   1         1              5         0.1182831      150497   8000
10  1         1              5         0.1182831      150497   8500
11  1         1              5         0.1182831      150497   9000
12  1         1              5         0.1182831      150497   9500
13  1         1              5         0.1182831      150497  10000
14  1         1              5         0.1182831      150497  10500
15  1         1              5         0.1182831      150497  11000
16  1         1              5         0.1182831      150497  11500
17  1         1              5         0.1182831      150497  12000
18  1         1              5         0.1182831      150497  12500
19  1         1              5         0.1182831      150497  13000
20  1         1              5         0.1182831      150497  13500
21  1         1              5         0.1182831      150497  14000
22  1         1              5         0.1182831      150497  14500
23  1         1              5         0.1182831      150497  15000
24  1         1              5         0.1182831      150497  15500
25  1         1              5         0.1182831      150497  16000
26  1         1              5         0.1182831      150497  16500
27  1         1              5         0.1182831      150497  17000
28  1         1              5         0.1182831      150497  17500
29  1         1              5         0.1182831      150497  18000
30  1         1              5         0.1182831      150497  18500
⋮   ⋮         ⋮              ⋮         ⋮              ⋮       ⋮
126 1         1              5         0.1182831      121349   4500
127 1         1              5         0.1182831      121349   5000
128 1         1              5         0.1182831      121349   5500
129 1         1              5         0.1182831      121349   6000
130 1         1              5         0.1182831      121349   6500
131 1         1              5         0.1182831      121349   7000
132 1         1              5         0.1182831      121349   7500
133 1         1              5         0.1182831      121349   8000
134 1         1              5         0.1182831      121349   8500
135 1         1              5         0.1182831      121349   9000
136 1         1              5         0.1182831      121349   9500
137 1         1              5         0.1182831      121349  10000
138 1         1              5         0.1182831      121349  10500
139 1         1              5         0.1182831      121349  11000
140 1         1              5         0.1182831      121349  11500
141 1         1              5         0.1182831      121349  12000
142 1         1              5         0.1182831      121349  12500
143 1         1              5         0.1182831      121349  13000
144 1         1              5         0.1182831      121349  13500
145 1         1              5         0.1182831      121349  14000
146 1         1              5         0.1182831      121349  14500
147 1         1              5         0.1182831      121349  15000
148 1         1              5         0.1182831      121349  15500
149 1         1              5         0.1182831      121349  16000
150 1         1              5         0.1182831      121349  16500
151 1         1              5         0.1182831      121349  17000
152 1         1              5         0.1182831      121349  17500
153 1         1              5         0.1182831      121349  18000
154 1         1              5         0.1182831      121349  18500
155 1         1              5         0.1182831      121349  19000
    ganancia_total ganancia_public_estimada ganancia_private_estimada
1   315700000      312583333                317035714
2   336050000      350441667                329882143
3   349800000      367858333                342060714
4   355850000      373083333                348464286
5   366300000      374458333                362803571
6   376750000      387750000                372035714
7   392700000      395908333                391325000
8   399850000      417450000                392307143
9   405900000      433583333                394035714
10  414150000      445316667                400792857
11  418000000      456225000                401617857
12  420750000      456591667                405389286
13  427900000      471441667                409239286
14  438350000      465391667                426760714
15  442200000      477766667                426957143
16  441650000      474741667                427467857
17  446600000      471441667                435953571
18  447150000      471625000                436660714
19  438900000      464750000                427821429
20  433950000      458608333                423382143
21  435600000      453750000                427821429
22  439450000      453750000                433321429
23  434500000      443941667                430453571
24  427350000      445500000                419571429
25  425700000      442016667                418707143
26  421850000      432391667                417332143
27  412500000      421025000                408846429
28  406450000      412133333                404014286
29  404800000      409383333                402835714
30  396550000      396000000                396785714
⋮   ⋮              ⋮                        ⋮
126 340450000      347325000                337503571
127 346500000      355300000                342728571
128 360250000      373725000                354475000
129 367400000      381700000                361271429
130 385550000      398200000                380128571
131 394900000      401500000                392071429
132 398750000      414516667                391992857
133 405900000      428175000                396353571
134 411950000      442475000                398867857
135 421300000      454208333                407196429
136 422950000      457875000                407982143
137 424600000      453658333                412146429
138 441650000      476300000                426800000
139 440000000      483083333                421535714
140 444950000      484183333                428135714
141 442200000      478225000                426760714
142 437250000      471533333                422557143
143 436700000      460441667                426525000
144 438350000      450816667                433007143
145 438900000      455308333                431867857
146 437250000      452650000                430650000
147 432300000      445775000                426525000
148 430650000      446325000                423932143
149 420200000      438350000                412421429
150 417450000      433400000                410614286
151 415800000      422675000                412853571
152 408650000      416808333                405153571
153 402600000      405533333                401342857
154 394350000      395175000                393996429
155 394900000      389125000                397375000

## Promedio de ganancias

`resumen_ganancias` muestra cada corte promediado sobre las `m` semillas. `mejor_corte_por_modelo` conserva el corte con mayor ganancia total promedio para cada conjunto de hiperparámetros.

In [27]:
resumen_metricas <- resultados_detalle[, .(
  ganancia_total_promedio = mean(ganancia_total),
  ganancia_total_sd = if (.N > 1L) sd(ganancia_total) else 0,
  ganancia_public_promedio = mean(ganancia_public_estimada),
  ganancia_private_promedio = mean(ganancia_private_estimada)
), by = .(modelo_id, envios)]

info_modelos <- mejores_modelos[, c(
  "ranking_origen",
  "id_origen",
  "metrica_origen",
  columnas_parametros
), with = FALSE]

info_modelos[, modelo_id := .I]

resumen_ganancias <- merge(
  info_modelos,
  resumen_metricas,
  by = "modelo_id"
)

setorder(
  resumen_ganancias,
  modelo_id,
  envios
)

resumen_ganancias[]

   modelo_id ranking_origen id_origen metrica_origen learning_rate
1  1         1              5         0.1182831      0.003697844
2  1         1              5         0.1182831      0.003697844
3  1         1              5         0.1182831      0.003697844
4  1         1              5         0.1182831      0.003697844
5  1         1              5         0.1182831      0.003697844
6  1         1              5         0.1182831      0.003697844
7  1         1              5         0.1182831      0.003697844
8  1         1              5         0.1182831      0.003697844
9  1         1              5         0.1182831      0.003697844
10 1         1              5         0.1182831      0.003697844
11 1         1              5         0.1182831      0.003697844
12 1         1              5         0.1182831      0.003697844
13 1         1              5         0.1182831      0.003697844
14 1         1              5         0.1182831      0.003697844
15 1         1              5         0.1182831      0.003697844
16 1         1              5         0.1182831      0.003697844
17 1         1              5         0.1182831      0.003697844
18 1         1              5         0.1182831      0.003697844
19 1         1              5         0.1182831      0.003697844
20 1         1              5         0.1182831      0.003697844
21 1         1              5         0.1182831      0.003697844
22 1         1              5         0.1182831      0.003697844
23 1         1              5         0.1182831      0.003697844
24 1         1              5         0.1182831      0.003697844
25 1         1              5         0.1182831      0.003697844
26 1         1              5         0.1182831      0.003697844
27 1         1              5         0.1182831      0.003697844
28 1         1              5         0.1182831      0.003697844
29 1         1              5         0.1182831      0.003697844
30 1         1              5         0.1182831      0.003697844
31 1         1              5         0.1182831      0.003697844
   num_iterations num_leaves min_sum_hessian_in_leaf envios
1  2780           24         0.06401048               4000
2  2780           24         0.06401048               4500
3  2780           24         0.06401048               5000
4  2780           24         0.06401048               5500
5  2780           24         0.06401048               6000
6  2780           24         0.06401048               6500
7  2780           24         0.06401048               7000
8  2780           24         0.06401048               7500
9  2780           24         0.06401048               8000
10 2780           24         0.06401048               8500
11 2780           24         0.06401048               9000
12 2780           24         0.06401048               9500
13 2780           24         0.06401048              10000
14 2780           24         0.06401048              10500
15 2780           24         0.06401048              11000
16 2780           24         0.06401048              11500
17 2780           24         0.06401048              12000
18 2780           24         0.06401048              12500
19 2780           24         0.06401048              13000
20 2780           24         0.06401048              13500
21 2780           24         0.06401048              14000
22 2780           24         0.06401048              14500
23 2780           24         0.06401048              15000
24 2780           24         0.06401048              15500
25 2780           24         0.06401048              16000
26 2780           24         0.06401048              16500
27 2780           24         0.06401048              17000
28 2780           24         0.06401048              17500
29 2780           24         0.06401048              18000
30 2780           24         0.06401048              18500
31 2780           24         0.06401048              19000
   ganancia_total_promedio ganancia_total_sd ganancia_public_promedio
1  316800000               4115823.1         311410000
2  338470000               1967739.8         341953333
3  348920000               2847279.4         359755000
4  357390000               4441058.4         371525000
5  369160000               4441058.4         378693333
6  382910000               3697702.0         390573333
7  390720000               2951609.7         398878333
8  398750000               3300000.0         418806667
9  406340000                983869.9         433546667
10 412390000               3263127.3         442731667
11 418220000               2626214.0         451293333
12 423610000               1998249.2         456243333
13 429000000               3390427.7         461303333
14 436150000               3730281.5         468581667
15 438680000               2508385.9         476776667
16 441210000               3530297.4         481323333
17 442420000               4288589.5         478041667
18 442530000               5355091.0         473275000
19 439560000               2649150.8         464585000
20 437470000               2847279.4         457013333
21 438900000               2333452.4         454391667
22 438790000               1475804.9         453823333
23 434720000               1631563.7         450083333
24 429110000               1998249.2         445683333
25 423280000               2508385.9         438001667
26 419430000               2951609.7         432465000
27 413160000               3169069.3         422528333
28 406890000               2281008.5         417248333
29 401280000               3052376.1         408430000
30 394570000               1631563.7         397705000
31 391380000               3425930.5         392535000
   ganancia_private_promedio
1  319110000
2  336977143
3  344276429
4  351332143
5  365074286
6  379625714
7  387223571
8  390154286
9  394680000
10 399386429
11 404045714
12 409624286
13 415155714
14 422250714
15 422352857
16 424018571
17 427153571
18 429353571
19 428835000
20 429094286
21 432260714
22 432347143
23 428135714
24 422007143
25 416970714
26 413843571
27 409145000
28 402450714
29 398215714
30 393226429
31 390885000

In [29]:
mejor_corte_por_modelo <- resumen_ganancias[
  order(modelo_id, -ganancia_total_promedio),
  .SD[1L],
  by = modelo_id
]

setorder(mejor_corte_por_modelo, -ganancia_total_promedio)
mejor_corte_por_modelo[]

  modelo_id ranking_origen id_origen metrica_origen learning_rate
1 1         1              5         0.1182831      0.003697844
  num_iterations num_leaves min_sum_hessian_in_leaf envios
1 2780           24         0.06401048              12500
  ganancia_total_promedio ganancia_total_sd ganancia_public_promedio
1 442530000               5355091           473275000
  ganancia_private_promedio
1 429353571