# Dos bayesianas con etiquetas estimadas para julio

Base: `z495_python_lags_doble.ipynb`.
La primera BO utiliza las etiquetas reales de marzo a junio y predice julio.
La segunda incorpora julio al entrenamiento y optimiza también `prob_corte`;
su validación utiliza solamente etiquetas reales de marzo a junio.

# Librerías

In [1]:
import os
import cudf
import cupy as cp
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd



from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
import optuna
from optuna.samplers import GPSampler
from optuna.trial import TrialState




print('cuDF:', cudf.__version__)
print('GPU:', cp.cuda.runtime.getDeviceProperties(0)['name'].decode())

cuDF: 26.08.01
GPU: NVIDIA GeForce RTX 3090

In [2]:
import lightgbm as lgb
import yaml
import rdata

In [3]:
# dispongo la carpeta con funciones e importo ternara. 
from pathlib import Path
import sys

# Obtiene la ruta del directorio actual y sube un nivel (.parent)
raiz_proyecto = Path().resolve().parent

# Agrega la ruta al sistema si no está ya incluida
if str(raiz_proyecto) not in sys.path:
  sys.path.append(str(raiz_proyecto))

# URLs

In [4]:
BASE_URL = os.path.join(
    os.path.expanduser("~"),
    "code", "DMEyF", "dmeyf2026"
)

DATA_FOLDER = os.path.join(BASE_URL, 'entregas', 'dataset')
DATA_URL = os.path.join(BASE_URL, "DATA")

EXP_URL = os.path.join(DATA_URL, "EXP")

DATA_TERNARIA_URL = os.path.join(DATA_FOLDER, 'competencia_01_ternaria.csv')
DATA_LAGS_URL = os.path.join(DATA_FOLDER, 'competencia_01_ternaria_lags.csv')
DATA_LAGS_FRAC_URL = os.path.join(DATA_FOLDER, 'competencia_01_ternaria_lf_k6_perdida4.csv')



carpeta_man_val = os.path.join(BASE_URL, "ensembles", "man_val")
archivo_validaciones = os.path.join(carpeta_man_val, "validaciones_manuales.csv")

experiment_name = "LAG-010"
experimento_segunda = "LAG-PSEUDO-001"
EXPERIMENT_URL = os.path.join(EXP_URL, experiment_name)

os.makedirs(EXPERIMENT_URL, exist_ok=True)

In [5]:
os.listdir(DATA_FOLDER)

['competencia_01_ternaria_lf_k6_perdida4.csv',
 'versiones_dataset_1.ipynb',
 'competencia_01_ternaria.csv',
 'competencia_01_crudo.csv',
 'competencia_01_ternaria_lags.csv']

# Constantes

In [6]:
SEED = 230047
future_segunda = [202108]

In [7]:
PARAM = {
    "experimento": experiment_name,
    "semilla_primigenia": SEED,
    "training_pct": 70,
    "train": [202103, 202104, 202105, 202106],
    "train_final": [202103, 202104, 202105, 202106],
    "future": [202107],
    "cortes": list(range(9_000, 15_001, 500)),
    "trainingstrategy": {"undersampling": 0.1},
    "hyperparametertuning": {
        "iteraciones": 200,
        "n_startup_trials": 60,
        "n_modelos_previos": 30,
        "xval_folds" : 3
    },
    "lgbm": {
        "param_fijos": {
            "boosting": "gbdt",
            "objective": "binary",
            # "metric": "auc",
            "metric": "average_precision",
            "feature_pre_filter": False,
            "first_metric_only": False,
            "boost_from_average": True,
            "force_row_wise": True,
            "deterministic": True,
            "verbosity": -100,
            "seed": SEED,
            "max_depth": -1,
            "min_gain_to_split": 0.0,
            "lambda_l1": 0.0,
            "lambda_l2": 0.0,
            "max_bin": 31,
            "bagging_fraction": 1.0,
            "pos_bagging_fraction": 1.0,
            "neg_bagging_fraction": 1.0,
            "is_unbalance": False,
            "scale_pos_weight": 1.0,
            "drop_rate": 0.1,
            "max_drop": 50,
            "skip_drop": 0.5,
            "extra_trees": False,
            "early_stopping": 0,
            "min_data_in_leaf": 0,
            "feature_fraction": 0.50,
            # "learning_rate": 0.005,
  
        }
    },
    "out": {"lgbm": {}},
}

# Lectura del dataset

In [8]:
# cudf no pandas -> GPU
df = cudf.read_csv(
    DATA_LAGS_FRAC_URL,
    dtype={'numero_de_cliente': 'int32', 'foto_mes': 'int32'}
)

In [9]:
df.head()

,numero_de_cliente,foto_mes,active_quarter,cliente_vip,internet,cliente_edad,cliente_antiguedad,mrentabilidad,mrentabilidad_annual,mcomisiones,...,Visa_madelantodolares_delta_lag_pond,Visa_fultimo_cierre_delta_lag_pond,Visa_mpagado_delta_lag_pond,Visa_mpagospesos_delta_lag_pond,Visa_mpagosdolares_delta_lag_pond,Visa_fechaalta_delta_lag_pond,Visa_mconsumototal_delta_lag_pond,Visa_cconsumos_delta_lag_pond,Visa_cadelantosefectivo_delta_lag_pond,Visa_mpagominimo_delta_lag_pond
0,12159854,202103,1,0,0,56,134,688.41,26701.84,98.82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12159854,202104,1,0,0,56,135,1622.57,27663.64,931.59,...,0.0,1.0,0.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0
2,12159854,202105,1,0,0,56,136,1987.98,28738.37,934.07,...,0.0,3.375,0.0,1.818989404e-12,0.0,42.25,0.0,0.0,0.0,0.0
3,12159854,202106,1,0,0,56,137,2580.75,29494.76,915.19,...,0.0,-3.346938776,0.0,1.818989404e-12,0.0,50.69387755,0.0,0.0,0.0,0.0
4,12159854,202107,1,0,0,56,138,2686.85,29431.10,688.94,...,0.0,1.191176471,0.0,3.637978807e-12,0.0,58.39705882,0.0,0.0,0.0,0.0

In [10]:
cudf.crosstab(df['ternaria'].fillna('NA'), df['foto_mes'])

foto_mes  202103  202104  202105  202106  202107  202108
ternaria
BAJA+1      1019     964    1143     874    1103       0
BAJA+2       960    1139     870    1098       0       0
NA             0       0       0       0  163245  164647
continua  160921  161181  161755  162142       0       0

In [11]:
df_completo = df.copy()

# Optimización de hiperparámetros

Dos BO consecutivas con el mismo espacio de hiperparámetros.
La cantidad de corridas y de inicializaciones se configura en `PARAM`.
Se inicializan con modelos de `validaciones_manuales.csv`, priorizando el dataset utilizado;
las demás inicializaciones se muestrean del espacio.

## Preprocesamiento

In [12]:
dataset_train_cpu = (
    df_completo
    .loc[df_completo["foto_mes"].isin(PARAM["train"])]
    .to_pandas()
    .reset_index(drop=True)
)

# Partición estratificada 70/30, equivalente a fold 1 y fold 2 en z495.
indices_fold_1, indices_fold_2 = train_test_split(
    np.arange(len(dataset_train_cpu)),
    train_size=PARAM["training_pct"] / 100,
    stratify=dataset_train_cpu["ternaria"],
    random_state=PARAM["semilla_primigenia"],
)

dataset_train_cpu["fold"] = np.int8(2)
dataset_train_cpu.loc[indices_fold_1, "fold"] = np.int8(1)

# BAJA+1 y BAJA+2 forman la clase positiva, igual que en el R.
dataset_train_cpu["clase01"] = (
    dataset_train_cpu["ternaria"].isin(["BAJA+1", "BAJA+2"])
    .astype(np.int8)
)

rng = np.random.default_rng(PARAM["semilla_primigenia"])
dataset_train_cpu["azar"] = rng.random(len(dataset_train_cpu))
dataset_train_cpu["training"] = (
    dataset_train_cpu["fold"].eq(1)
    & (
        (dataset_train_cpu["azar"] <= PARAM["trainingstrategy"]["undersampling"])
        | dataset_train_cpu["ternaria"].isin(["BAJA+1", "BAJA+2"])
    )
).astype(np.int8)

columnas_excluidas = {
    "ternaria",
    "ternaria_lag1",
    "clase01",
    "fold",
    "azar",
    "training",
    "cprestamos_personales",
    "cprestamos_personales_lag1",
    "cprestamos_personales_delta1",
    "mprestamos_personales",
    "mprestamos_personales_lag1",
    "mprestamos_personales_delta1"
}

campos_buenos = [
    columna
    for columna in dataset_train_cpu.columns
    if columna not in columnas_excluidas
]

mask_training = dataset_train_cpu["training"].eq(1)
X_train_bo = dataset_train_cpu.loc[mask_training, campos_buenos]
y_train_bo = dataset_train_cpu.loc[mask_training, "clase01"]

# Replica literalmente z495: validation contiene todas las filas con training == 0.
mask_validation = dataset_train_cpu["training"].eq(0)
X_validate_bo = dataset_train_cpu.loc[mask_validation, campos_buenos]
y_validate_bo = dataset_train_cpu.loc[mask_validation, "clase01"]

dtrain = lgb.Dataset(
    data=X_train_bo,
    label=y_train_bo,
    feature_name=campos_buenos,
    free_raw_data=False,
)

dvalidate = lgb.Dataset(
    data=X_validate_bo,
    label=y_validate_bo,
    feature_name=campos_buenos,
    free_raw_data=False,
)

print("Filas para training:", len(X_train_bo))
print("Filas para validation:", len(X_validate_bo))
print("Columnas:", len(campos_buenos))
dataset_train_cpu.groupby(["fold", "ternaria", "training"]).size()

Filas para training: 50866
Filas para validation: 603200
Columnas: 456

fold  ternaria  training
1     BAJA+1    1             2800
      BAJA+2    1             2847
      continua  0           406980
                1            45219
2     BAJA+1    0             1200
      BAJA+2    0             1220
      continua  0           193800
dtype: int64

## Función objetivo: Average Precision sobre validation

In [13]:
def estimar_auc_lightgbm(parametros_variables):
    parametros_completos = {
        **PARAM["lgbm"]["param_fijos"],
        **parametros_variables,
    }

    # En Python conviene pasar el número de árboles por su argumento dedicado.
    num_boost_round = int(parametros_completos.pop("num_iterations"))

    resultados_cv = lgb.cv(
        params=parametros_completos,
        train_set=dtrain,
        num_boost_round=num_boost_round,
        nfold=PARAM["hyperparametertuning"]["xval_folds"],
        stratified=True,
        shuffle=True,
        seed=PARAM["semilla_primigenia"],
    )

    clave_auc = next(
        clave for clave in resultados_cv
        if clave.endswith("auc-mean")
    )

    # Sin early stopping, equivale al score al finalizar num_iterations.
    return float(resultados_cv[clave_auc][-1])

In [14]:
def estimar_ap_lightgbm(parametros_variables):
    parametros_variables = parametros_variables.copy()
    prob_corte = parametros_variables.pop("prob_corte", None)

    if prob_corte is None:
        dtrain_bo = dtrain
    else:
        clase_julio = np.isin(etiquetar_julio(prob_corte), ["BAJA+1", "BAJA+2"])
        training_julio = (
            (azar_julio <= PARAM["trainingstrategy"]["undersampling"])
            | clase_julio
        )
        dtrain_bo = lgb.Dataset(
            data=pd.concat(
                [X_train_bo, dataset_julio_cpu.loc[training_julio, campos_buenos]],
                ignore_index=True,
            ),
            label=np.concatenate([y_train_bo.to_numpy(), clase_julio[training_julio]]),
            feature_name=campos_buenos,
        )

    parametros_completos = {
        **PARAM["lgbm"]["param_fijos"],
        **parametros_variables,
    }

    num_boost_round = int(parametros_completos.pop("num_iterations"))

    modelo = lgb.train(
        params=parametros_completos,
        train_set=dtrain_bo,
        num_boost_round=num_boost_round,
        valid_sets=[dvalidate],
        valid_names=["val"],
    )

    return float(modelo.best_score["val"]["average_precision"])

In [15]:
ganancia_validate_bo = np.where(
    dataset_train_cpu.loc[mask_validation, "ternaria"].eq("BAJA+2"),
    1_072_500,
    -27_500,
)


def estimar_ganancia_lightgbm(parametros_variables):
    parametros_completos = {
        **PARAM["lgbm"]["param_fijos"],
        **parametros_variables,
    }

    num_boost_round = int(
        parametros_completos.pop("num_iterations")
    )

    modelo = lgb.train(
        params=parametros_completos,
        train_set=dtrain,
        num_boost_round=num_boost_round,
    )

    prediccion = modelo.predict(X_validate_bo)
    orden = np.argsort(-prediccion)

    ganancia_acumulada = np.cumsum(
        ganancia_validate_bo[orden]
    )

    return float(ganancia_acumulada.max())

In [16]:
rangos_bo = {'num_iterations': (400, 4000),
 'num_leaves': (16, 2048),
 'feature_fraction': (0.1, 0.75),
 'min_sum_hessian_in_leaf': (0.0001, 0.1),
 'learning_rate': (0.002, 0.025),
 'min_data_in_leaf': (0, 1000),
 'scale_pos_weight': (0.5, 1.0)}

def objective(trial):
    parametros_variables = {
        "num_iterations": trial.suggest_int(
            "num_iterations", *rangos_bo["num_iterations"]
        ),
        "num_leaves": trial.suggest_int(
            "num_leaves", *rangos_bo["num_leaves"], log=True
        ),
        "feature_fraction": trial.suggest_float(
            "feature_fraction", *rangos_bo["feature_fraction"]
        ),
        "min_sum_hessian_in_leaf": trial.suggest_float(
            "min_sum_hessian_in_leaf",
            *rangos_bo["min_sum_hessian_in_leaf"],
            log=True,
        ),
        "learning_rate": trial.suggest_float(
            "learning_rate", *rangos_bo["learning_rate"], log=True
        ),
        "min_data_in_leaf": trial.suggest_int(
            "min_data_in_leaf",
            *rangos_bo["min_data_in_leaf"],
            log=rangos_bo["min_data_in_leaf"][0] > 0,
        ),
    }
    if "scale_pos_weight" in rangos_bo:
        parametros_variables["scale_pos_weight"] = trial.suggest_float(
            "scale_pos_weight", *rangos_bo["scale_pos_weight"]
        )
    if "prob_corte" in rangos_bo:
        parametros_variables["prob_corte"] = trial.suggest_float(
            "prob_corte", *rangos_bo["prob_corte"]
        )
    return estimar_ap_lightgbm(parametros_variables)
    # return estimar_auc_lightgbm(parametros_variables)
    # return estimar_ganancia_lightgbm(parametros_variables)

## Modelos para las inicializaciones

In [17]:
# Misma conversión de RDS usada en la validación manual Python.
def convertir_r(valor):
    if isinstance(valor, dict):
        return {k: convertir_r(v) for k, v in valor.items()}
    if isinstance(valor, np.ndarray):
        if valor.size == 1:
            return convertir_r(valor.item())
        return [convertir_r(v) for v in valor.tolist()]
    if isinstance(valor, (list, tuple)):
        return [convertir_r(v) for v in valor]
    if isinstance(valor, np.generic):
        return convertir_r(valor.item())
    if isinstance(valor, float) and np.isfinite(valor) and valor.is_integer():
        return int(valor)
    return valor

validaciones = pd.read_csv(archivo_validaciones)
validaciones = validaciones.sort_values("ganancia", ascending=False)
dataset_file = os.path.basename(DATA_LAGS_FRAC_URL)
es_dataset_actual = validaciones["dataset"].eq(dataset_file)
modelos_iniciales = pd.concat([
    validaciones.loc[es_dataset_actual],
    validaciones.loc[~es_dataset_actual],
]).head(PARAM["hyperparametertuning"]["n_modelos_previos"])

puntos_iniciales_bo = []
for id_validacion in modelos_iniciales["id_validacion"]:
    parametros = convertir_r(rdata.read_rds(
        os.path.join(carpeta_man_val, f"{int(id_validacion)}.rds")
    ))
    if "num_iterations" not in parametros:
        parametros = next(iter(parametros.values()))
    parametros = parametros.copy()
    # El RDS guarda este parámetro ajustado para entrenar sin undersampling.
    parametros["min_data_in_leaf"] = int(np.rint(
        parametros["min_data_in_leaf"] * PARAM["trainingstrategy"]["undersampling"]
    ))
    puntos_iniciales_bo.append({
        nombre: parametros.get(nombre, PARAM["lgbm"]["param_fijos"].get(nombre))
        for nombre in rangos_bo
    })

modelos_iniciales

,id_validacion,ganancia,seeds,dataset,cantidad_registros_totales,cantidad_registros_entrenamiento,cantidad_registros_validacion,meses_entrenamiento,meses_validacion,columnas_excluidas,benchmark_original
50,51,474831500,"230047,230059,230063,230077,230081",competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_090149
43,44,474831500,"230047,230059,230063,230077,230081",competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_090149
38,39,474831500,"230047,230059,230063,230077,230081",competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_123618
31,32,473517000,"230047,230059,230063,230077,230081",competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_090643
42,43,473517000,"230047,230059,230063,230077,230081",competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_090643
27,28,473357500,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_090149
28,29,472230000,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_090643
47,48,465883000,"230047,230059,230063,230077,230081",competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_084709
34,35,465883000,"230047,230059,230063,230077,230081",competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_132722
32,33,465883000,"230047,230059,230063,230077,230081",competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_132722
46,47,465883000,"230047,230059,230063,230077,230081",competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_085726
39,40,465294500,"230047,230059,230063,230077,230081",competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_114539
35,36,464920500,"230047,230059,230063,230077,230081",competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_131032
17,18,464667500,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260921_110853
23,24,463952500,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_084709
24,25,463952500,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_085726
5,6,460295000,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,163284,164114,202104,202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260921_151032
8,9,460267500,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,163284,164114,202104,202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260921_153324
16,17,458782500,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260921_124327
4,5,457242500,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,163284,164114,202104,202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260921_110853
12,13,454052500,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,163284,164114,202104,202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260921_160353
1,2,452017500,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,163284,164114,202104,202106,"ternaria,clase01,fold,azar,training,cprestamos...",benchmark_multisemilla_lags20260921_124327
9,10,452017500,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,163284,164114,202104,202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260921_154456
20,21,432575000,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260923_130520
19,20,432575000,NaN,competencia_01_ternaria_lf_k6_perdida4.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260923_122451
29,30,474897500,NaN,competencia_01_ternaria_lags.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_090643
40,41,474281500,"230047,230059,230063,230077,230081",competencia_01_ternaria_lags.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_114539
44,45,472384000,"230047,230059,230063,230077,230081",competencia_01_ternaria_lags.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_090149
37,38,472384000,"230047,230059,230063,230077,230081",competencia_01_ternaria_lags.csv,983061,326184,164114,"202103,202104",202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260924_123618
3,4,471872500,NaN,competencia_01_ternaria_lags.csv,983061,163284,164114,202104,202106,"ternaria,ternaria_lag1,clase01,fold,azar,train...",benchmark_multisemilla_lags20260921_110853

## Estudio Optuna y reanudación

In [18]:
n_startup_trials = PARAM["hyperparametertuning"]["n_startup_trials"]
n_trials_total = PARAM["hyperparametertuning"]["iteraciones"]

sampler = GPSampler(
    seed=PARAM["semilla_primigenia"],
    n_startup_trials=n_startup_trials,
    deterministic_objective=False,
)

study_db_url = os.path.join(EXPERIMENT_URL, "optuna_study.db")
storage_url = f"sqlite:///{study_db_url}"

study = optuna.create_study(
    study_name=experiment_name,
    direction="maximize",
    sampler=sampler,
    storage=storage_url,
    load_if_exists=True,
)

# Se encolan solamente al crear el estudio; conserva también HP repetidos.
if not study.trials:
    for punto in puntos_iniciales_bo:
        study.enqueue_trial(punto)

/tmp/ipykernel_397057/96132893.py:4: ExperimentalWarning: GPSampler is experimental (supported from v3.6.0). The interface can change in the future.
  sampler = GPSampler(
[I 2026-10-05 23:27:32,088] A new study created in RDB with name: LAG-010

In [19]:
trials_completos = sum(
    trial.state == TrialState.COMPLETE
    for trial in study.trials
)
trials_restantes = max(0, n_trials_total - trials_completos)

print("Trials completos:", trials_completos)
print("Trials restantes:", trials_restantes)

if trials_restantes > 0:
    study.optimize(
        objective,
        n_trials=trials_restantes,
        show_progress_bar=True,
    )
else:
    print("c'est fini")

Trials completos: 0
Trials restantes: 200

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-10-05 23:27:58,576] Trial 0 finished with value: 0.12584029556988666 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5}. Best is trial 0 with value: 0.12584029556988666.
[I 2026-10-05 23:28:15,885] Trial 1 finished with value: 0.12584029556988666 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5}. Best is trial 0 with value: 0.12584029556988666.
[I 2026-10-05 23:28:32,624] Trial 2 finished with value: 0.12584029556988666 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5}. Best is trial 0 with value: 0.12584029556988666.
[I 2026-10-05 23:29:15,044] Trial 3 finished with value: 0.12731982780231527 and parameters: {'num_iterations': 1067, 'num_leaves': 2048, 'feature_fraction': 0.35, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00675493259696748, 'min_data_in_leaf': 168, 'scale_pos_weight': 0.5}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:29:59,878] Trial 4 finished with value: 0.12731982780231527 and parameters: {'num_iterations': 1067, 'num_leaves': 2048, 'feature_fraction': 0.35, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00675493259696748, 'min_data_in_leaf': 168, 'scale_pos_weight': 0.5}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:30:18,205] Trial 5 finished with value: 0.12584029556988666 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:31:05,702] Trial 6 finished with value: 0.12731982780231527 and parameters: {'num_iterations': 1067, 'num_leaves': 2048, 'feature_fraction': 0.35, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00675493259696748, 'min_data_in_leaf': 168, 'scale_pos_weight': 0.5}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:31:59,132] Trial 7 finished with value: 0.11866932567758728 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:32:47,453] Trial 8 finished with value: 0.11866932567758728 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:33:39,406] Trial 9 finished with value: 0.11866932567758728 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:34:35,544] Trial 10 finished with value: 0.11866932567758728 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:34:52,479] Trial 11 finished with value: 0.12673009791050333 and parameters: {'num_iterations': 454, 'num_leaves': 256, 'feature_fraction': 0.264156247389931, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0185711199192682, 'min_data_in_leaf': 181, 'scale_pos_weight': 0.5}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:35:32,434] Trial 12 finished with value: 0.11701622022934076 and parameters: {'num_iterations': 1345, 'num_leaves': 43, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00276306526156717, 'min_data_in_leaf': 52, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:35:48,182] Trial 13 finished with value: 0.11196343943207294 and parameters: {'num_iterations': 611, 'num_leaves': 20, 'feature_fraction': 0.552791861343054, 'min_sum_hessian_in_leaf': 0.0377107584841935, 'learning_rate': 0.01, 'min_data_in_leaf': 0, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:36:40,906] Trial 14 finished with value: 0.11866932567758728 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:37:35,309] Trial 15 finished with value: 0.11866932567758728 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.

/home/marco/anaconda3/envs/cmeyf-cuda13/lib/python3.11/site-packages/optuna/trial/_trial.py:664: UserWarning: Fixed parameter min_sum_hessian_in_leaf with value 1e-06 is out of range for distribution FloatDistribution(high=0.1, log=True, low=0.0001, step=None).
  optuna_warn(

[I 2026-10-05 23:38:27,226] Trial 16 finished with value: 0.11197237478493562 and parameters: {'num_iterations': 2152, 'num_leaves': 16, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 1e-06, 'learning_rate': 0.004, 'min_data_in_leaf': 0, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:39:36,283] Trial 17 finished with value: 0.11431038175128952 and parameters: {'num_iterations': 2837, 'num_leaves': 16, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 1e-06, 'learning_rate': 0.004, 'min_data_in_leaf': 0, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:39:55,440] Trial 18 finished with value: 0.12684003672548586 and parameters: {'num_iterations': 712, 'num_leaves': 86, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 1e-06, 'learning_rate': 0.00757969257611117, 'min_data_in_leaf': 0, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:40:09,086] Trial 19 finished with value: 0.11196343943207294 and parameters: {'num_iterations': 611, 'num_leaves': 20, 'feature_fraction': 0.552791861343054, 'min_sum_hessian_in_leaf': 0.0377107584841935, 'learning_rate': 0.01, 'min_data_in_leaf': 0, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.12731982780231527.
[I 2026-10-05 23:40:31,904] Trial 20 finished with value: 0.1297361085926484 and parameters: {'num_iterations': 715, 'num_leaves': 164, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.006, 'min_data_in_leaf': 0, 'scale_pos_weight': 1}. Best is trial 20 with value: 0.1297361085926484.
[I 2026-10-05 23:40:50,934] Trial 21 finished with value: 0.12684003672548586 and parameters: {'num_iterations': 712, 'num_leaves': 86, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 1e-06, 'learning_rate': 0.00757969257611117, 'min_data_in_leaf': 0, 'scale_pos_weight': 1}. Best is trial 20 with value: 0.1297361085926484.
[I 2026-10-05 23:41:09,915] Trial 22 finished with value: 0.12684003672548586 and parameters: {'num_iterations': 712, 'num_leaves': 86, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 1e-06, 'learning_rate': 0.00757969257611117, 'min_data_in_leaf': 0, 'scale_pos_weight': 1}. Best is trial 20 with value: 0.1297361085926484.
[I 2026-10-05 23:42:16,874] Trial 23 finished with value: 0.13999913113911264 and parameters: {'num_iterations': 2140, 'num_leaves': 133, 'feature_fraction': 0.536030890639101, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.02, 'min_data_in_leaf': 0, 'scale_pos_weight': 1}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:43:24,191] Trial 24 finished with value: 0.13999913113911264 and parameters: {'num_iterations': 2140, 'num_leaves': 133, 'feature_fraction': 0.536030890639101, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.02, 'min_data_in_leaf': 0, 'scale_pos_weight': 1}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:44:03,461] Trial 25 finished with value: 0.12731982780231527 and parameters: {'num_iterations': 1067, 'num_leaves': 2048, 'feature_fraction': 0.35, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00675493259696748, 'min_data_in_leaf': 168, 'scale_pos_weight': 0.5}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:44:18,460] Trial 26 finished with value: 0.12673009791050333 and parameters: {'num_iterations': 454, 'num_leaves': 256, 'feature_fraction': 0.264156247389931, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0185711199192682, 'min_data_in_leaf': 181, 'scale_pos_weight': 0.5}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:44:35,933] Trial 27 finished with value: 0.12584029556988666 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:44:50,543] Trial 28 finished with value: 0.12584029556988666 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:45:04,509] Trial 29 finished with value: 0.11196343943207294 and parameters: {'num_iterations': 611, 'num_leaves': 20, 'feature_fraction': 0.552791861343054, 'min_sum_hessian_in_leaf': 0.0377107584841935, 'learning_rate': 0.01, 'min_data_in_leaf': 0, 'scale_pos_weight': 1}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:45:25,945] Trial 30 finished with value: 0.12223062970017004 and parameters: {'num_iterations': 733, 'num_leaves': 143, 'feature_fraction': 0.5434842189094079, 'min_sum_hessian_in_leaf': 0.00014565936056512924, 'learning_rate': 0.014064239786361173, 'min_data_in_leaf': 623, 'scale_pos_weight': 0.522463633354189}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:47:06,075] Trial 31 finished with value: 0.12649501143760067 and parameters: {'num_iterations': 2953, 'num_leaves': 329, 'feature_fraction': 0.7033917176710153, 'min_sum_hessian_in_leaf': 0.0029083349011123924, 'learning_rate': 0.00863277737418505, 'min_data_in_leaf': 460, 'scale_pos_weight': 0.6295581827605774}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:49:05,647] Trial 32 finished with value: 0.12570845676009454 and parameters: {'num_iterations': 3203, 'num_leaves': 208, 'feature_fraction': 0.5378131899900485, 'min_sum_hessian_in_leaf': 0.00010290623073077732, 'learning_rate': 0.010073106655143264, 'min_data_in_leaf': 232, 'scale_pos_weight': 0.9929906378932698}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:49:43,379] Trial 33 finished with value: 0.11634320632578501 and parameters: {'num_iterations': 1545, 'num_leaves': 228, 'feature_fraction': 0.2592367727496495, 'min_sum_hessian_in_leaf': 0.00010376267234933979, 'learning_rate': 0.006505847275410017, 'min_data_in_leaf': 908, 'scale_pos_weight': 0.8563837282331693}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:50:43,000] Trial 34 finished with value: 0.12556486285993465 and parameters: {'num_iterations': 1849, 'num_leaves': 113, 'feature_fraction': 0.2851661480405878, 'min_sum_hessian_in_leaf': 0.00014825668069176127, 'learning_rate': 0.0223203063204339, 'min_data_in_leaf': 307, 'scale_pos_weight': 0.5372704116918032}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:50:56,163] Trial 35 finished with value: 0.09579168235770875 and parameters: {'num_iterations': 548, 'num_leaves': 422, 'feature_fraction': 0.12476442243711575, 'min_sum_hessian_in_leaf': 0.00030587979645571865, 'learning_rate': 0.010522910382689543, 'min_data_in_leaf': 998, 'scale_pos_weight': 0.92562926103497}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:52:40,117] Trial 36 finished with value: 0.13188333494849205 and parameters: {'num_iterations': 2180, 'num_leaves': 1096, 'feature_fraction': 0.34114293739172863, 'min_sum_hessian_in_leaf': 0.004781669248283792, 'learning_rate': 0.00888409080450627, 'min_data_in_leaf': 110, 'scale_pos_weight': 0.5134619619738492}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:54:07,844] Trial 37 finished with value: 0.12003919057853339 and parameters: {'num_iterations': 2746, 'num_leaves': 405, 'feature_fraction': 0.5612819753602661, 'min_sum_hessian_in_leaf': 0.0016405466751312236, 'learning_rate': 0.018104975051898734, 'min_data_in_leaf': 688, 'scale_pos_weight': 0.6925901347795324}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:55:28,561] Trial 38 finished with value: 0.1280902574934644 and parameters: {'num_iterations': 3505, 'num_leaves': 38, 'feature_fraction': 0.2839699176693974, 'min_sum_hessian_in_leaf': 0.0005776310137077564, 'learning_rate': 0.010338859498794354, 'min_data_in_leaf': 261, 'scale_pos_weight': 0.8390274552440498}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:57:14,619] Trial 39 finished with value: 0.12883583151446582 and parameters: {'num_iterations': 2725, 'num_leaves': 207, 'feature_fraction': 0.5553148306288307, 'min_sum_hessian_in_leaf': 0.014945555161007432, 'learning_rate': 0.0023387880359002815, 'min_data_in_leaf': 151, 'scale_pos_weight': 0.6252415403324905}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-05 23:58:55,546] Trial 40 finished with value: 0.12021696780616802 and parameters: {'num_iterations': 3882, 'num_leaves': 1583, 'feature_fraction': 0.44584784048181647, 'min_sum_hessian_in_leaf': 0.00017845743197516685, 'learning_rate': 0.00706629849097512, 'min_data_in_leaf': 894, 'scale_pos_weight': 0.5776244558851937}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:00:04,026] Trial 41 finished with value: 0.11963567697908564 and parameters: {'num_iterations': 2660, 'num_leaves': 21, 'feature_fraction': 0.5925580471112588, 'min_sum_hessian_in_leaf': 0.00014111306866150934, 'learning_rate': 0.005613812536129389, 'min_data_in_leaf': 304, 'scale_pos_weight': 0.5001934126063887}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:00:29,926] Trial 42 finished with value: 0.12311442495893629 and parameters: {'num_iterations': 766, 'num_leaves': 218, 'feature_fraction': 0.5459327624622321, 'min_sum_hessian_in_leaf': 0.004586928712049362, 'learning_rate': 0.022029052122176495, 'min_data_in_leaf': 634, 'scale_pos_weight': 0.5911768910899599}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:01:08,175] Trial 43 finished with value: 0.10118186242386158 and parameters: {'num_iterations': 1672, 'num_leaves': 28, 'feature_fraction': 0.10794855054141235, 'min_sum_hessian_in_leaf': 0.0008166620702590977, 'learning_rate': 0.004118521660508839, 'min_data_in_leaf': 990, 'scale_pos_weight': 0.5121494933174109}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:02:31,043] Trial 44 finished with value: 0.12339065102014757 and parameters: {'num_iterations': 3062, 'num_leaves': 43, 'feature_fraction': 0.41922301102691595, 'min_sum_hessian_in_leaf': 0.00015013848831063056, 'learning_rate': 0.002648092343016029, 'min_data_in_leaf': 249, 'scale_pos_weight': 0.8665915277913694}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:04:07,374] Trial 45 finished with value: 0.11975282206984422 and parameters: {'num_iterations': 3217, 'num_leaves': 1387, 'feature_fraction': 0.5795486658333552, 'min_sum_hessian_in_leaf': 0.000717236630317424, 'learning_rate': 0.006860350095018485, 'min_data_in_leaf': 996, 'scale_pos_weight': 0.7657036144865936}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:05:08,076] Trial 46 finished with value: 0.10470542593742181 and parameters: {'num_iterations': 2481, 'num_leaves': 20, 'feature_fraction': 0.2284768717107649, 'min_sum_hessian_in_leaf': 0.0011618761234941347, 'learning_rate': 0.002452829234204884, 'min_data_in_leaf': 765, 'scale_pos_weight': 0.9746552041884009}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:05:33,636] Trial 47 finished with value: 0.11015376575240773 and parameters: {'num_iterations': 917, 'num_leaves': 41, 'feature_fraction': 0.44974099035533577, 'min_sum_hessian_in_leaf': 0.010659281229048176, 'learning_rate': 0.002229917970107745, 'min_data_in_leaf': 98, 'scale_pos_weight': 0.9130595136674472}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:07:20,542] Trial 48 finished with value: 0.1199724914260443 and parameters: {'num_iterations': 3375, 'num_leaves': 178, 'feature_fraction': 0.6509060655572582, 'min_sum_hessian_in_leaf': 0.009115698007240651, 'learning_rate': 0.008691127884990296, 'min_data_in_leaf': 867, 'scale_pos_weight': 0.840983285622334}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:08:11,929] Trial 49 finished with value: 0.11759539907453308 and parameters: {'num_iterations': 1757, 'num_leaves': 758, 'feature_fraction': 0.7038280386244882, 'min_sum_hessian_in_leaf': 0.0014359453428571646, 'learning_rate': 0.019707412750131097, 'min_data_in_leaf': 997, 'scale_pos_weight': 0.9825839036064627}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:09:07,618] Trial 50 finished with value: 0.1306075279083013 and parameters: {'num_iterations': 1421, 'num_leaves': 234, 'feature_fraction': 0.4821516836412084, 'min_sum_hessian_in_leaf': 0.003749262347103061, 'learning_rate': 0.0075917644413380884, 'min_data_in_leaf': 128, 'scale_pos_weight': 0.5264633009641988}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:10:03,195] Trial 51 finished with value: 0.12447582633237617 and parameters: {'num_iterations': 1961, 'num_leaves': 117, 'feature_fraction': 0.3815409904947995, 'min_sum_hessian_in_leaf': 0.059533554609152356, 'learning_rate': 0.01761084578322779, 'min_data_in_leaf': 569, 'scale_pos_weight': 0.933504734661122}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:11:34,387] Trial 52 finished with value: 0.12447668230963188 and parameters: {'num_iterations': 2790, 'num_leaves': 355, 'feature_fraction': 0.3605960342098665, 'min_sum_hessian_in_leaf': 0.08866999121969253, 'learning_rate': 0.015772797046473323, 'min_data_in_leaf': 391, 'scale_pos_weight': 0.9143598142210787}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:12:42,548] Trial 53 finished with value: 0.1258273655924968 and parameters: {'num_iterations': 2593, 'num_leaves': 28, 'feature_fraction': 0.6826267607713525, 'min_sum_hessian_in_leaf': 0.0014433712179007787, 'learning_rate': 0.01702315758311984, 'min_data_in_leaf': 360, 'scale_pos_weight': 0.8609851244668393}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:14:01,302] Trial 54 finished with value: 0.1339378111810657 and parameters: {'num_iterations': 2910, 'num_leaves': 75, 'feature_fraction': 0.3235840202698614, 'min_sum_hessian_in_leaf': 0.07331144282260937, 'learning_rate': 0.006735916655838257, 'min_data_in_leaf': 51, 'scale_pos_weight': 0.913028009878796}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:15:10,435] Trial 55 finished with value: 0.12059261022484137 and parameters: {'num_iterations': 2258, 'num_leaves': 196, 'feature_fraction': 0.5037319351198142, 'min_sum_hessian_in_leaf': 0.027960020937887405, 'learning_rate': 0.00734676115549613, 'min_data_in_leaf': 860, 'scale_pos_weight': 0.5600405295666462}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:15:37,268] Trial 56 finished with value: 0.08243835941960927 and parameters: {'num_iterations': 839, 'num_leaves': 37, 'feature_fraction': 0.6849366723465027, 'min_sum_hessian_in_leaf': 0.006492838304029793, 'learning_rate': 0.002759884395466478, 'min_data_in_leaf': 806, 'scale_pos_weight': 0.8976611170895026}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:17:02,846] Trial 57 finished with value: 0.13173922153585788 and parameters: {'num_iterations': 2477, 'num_leaves': 267, 'feature_fraction': 0.23360971912417045, 'min_sum_hessian_in_leaf': 0.006395476122150491, 'learning_rate': 0.0185994253832688, 'min_data_in_leaf': 150, 'scale_pos_weight': 0.9048692544539163}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:17:39,693] Trial 58 finished with value: 0.11691262497620002 and parameters: {'num_iterations': 1620, 'num_leaves': 16, 'feature_fraction': 0.7129218699393903, 'min_sum_hessian_in_leaf': 0.00013340655405408078, 'learning_rate': 0.00824273293683794, 'min_data_in_leaf': 305, 'scale_pos_weight': 0.9959193019834933}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:19:11,269] Trial 59 finished with value: 0.1249336628333422 and parameters: {'num_iterations': 2908, 'num_leaves': 340, 'feature_fraction': 0.5726348324104491, 'min_sum_hessian_in_leaf': 0.018977524996342362, 'learning_rate': 0.01170092239297866, 'min_data_in_leaf': 499, 'scale_pos_weight': 0.714073312889434}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:20:18,425] Trial 60 finished with value: 0.13956976098975618 and parameters: {'num_iterations': 1538, 'num_leaves': 281, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0004736330772107053, 'learning_rate': 0.01940488729797924, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:21:20,495] Trial 61 finished with value: 0.13782078502645306 and parameters: {'num_iterations': 1946, 'num_leaves': 143, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.011038637278558958, 'learning_rate': 0.01670182333332935, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}. Best is trial 23 with value: 0.13999913113911264.
[I 2026-10-06 00:22:20,272] Trial 62 finished with value: 0.14285669904347578 and parameters: {'num_iterations': 1698, 'num_leaves': 226, 'feature_fraction': 0.36428760707582264, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.013990790377427736, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}. Best is trial 62 with value: 0.14285669904347578.
[I 2026-10-06 00:23:33,469] Trial 63 finished with value: 0.138224321891565 and parameters: {'num_iterations': 1718, 'num_leaves': 470, 'feature_fraction': 0.2606129821746312, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.00713741645520979, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}. Best is trial 62 with value: 0.14285669904347578.
[I 2026-10-06 00:24:15,554] Trial 64 finished with value: 0.1374570636340413 and parameters: {'num_iterations': 1483, 'num_leaves': 206, 'feature_fraction': 0.12078196949616579, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.024422998350535394, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}. Best is trial 62 with value: 0.14285669904347578.
[I 2026-10-06 00:25:17,424] Trial 65 finished with value: 0.1405055718288816 and parameters: {'num_iterations': 1715, 'num_leaves': 195, 'feature_fraction': 0.4953092714277332, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.012227669014306436, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}. Best is trial 62 with value: 0.14285669904347578.
[I 2026-10-06 00:26:17,098] Trial 66 finished with value: 0.13893254866756818 and parameters: {'num_iterations': 1466, 'num_leaves': 323, 'feature_fraction': 0.4221436770176994, 'min_sum_hessian_in_leaf': 0.0002909368918445891, 'learning_rate': 0.020730854676600043, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}. Best is trial 62 with value: 0.14285669904347578.
[I 2026-10-06 00:27:08,677] Trial 67 finished with value: 0.13378355537092582 and parameters: {'num_iterations': 1796, 'num_leaves': 238, 'feature_fraction': 0.1, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.013537461014039933, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}. Best is trial 62 with value: 0.14285669904347578.
[I 2026-10-06 00:27:58,897] Trial 68 finished with value: 0.14079856407296024 and parameters: {'num_iterations': 1664, 'num_leaves': 146, 'feature_fraction': 0.3389984114813787, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.025, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}. Best is trial 62 with value: 0.14285669904347578.
[I 2026-10-06 00:31:01,373] Trial 69 finished with value: 0.12119485454912148 and parameters: {'num_iterations': 1859, 'num_leaves': 2048, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0049024770177285215, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}. Best is trial 62 with value: 0.14285669904347578.

## Resultados de la optimización

In [20]:
tb_bayesiana = study.trials_dataframe()
tb_bayesiana["iter"] = np.arange(1, len(tb_bayesiana) + 1)
tb_bayesiana = (
    tb_bayesiana
    .sort_values("value", ascending=False, na_position="last")
    .reset_index(drop=True)
)
tb_bayesiana.to_csv(
    os.path.join(EXPERIMENT_URL, "BO_log.txt"),
    sep="	",
    index=False,
)

PARAM["out"]["lgbm"]["mejores_hiperparametros"] = dict(study.best_trial.params)
PARAM["out"]["lgbm"]["y"] = float(study.best_value)

with open(os.path.join(EXPERIMENT_URL, "PARAM.yml"), "w", encoding="utf-8") as archivo:
    yaml.safe_dump(PARAM, archivo, sort_keys=False, allow_unicode=True)

print(PARAM["out"]["lgbm"]["mejores_hiperparametros"])
print("Mejor Average Precision:", PARAM["out"]["lgbm"]["y"])
tb_bayesiana.head()

{'num_iterations': 4000, 'num_leaves': 166, 'feature_fraction': 0.27641343005495034, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.011685329568129043, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}
Mejor Average Precision: 0.14422319332138248

,number,value,datetime_start,datetime_complete,duration,params_feature_fraction,params_learning_rate,params_min_data_in_leaf,params_min_sum_hessian_in_leaf,params_num_iterations,params_num_leaves,params_scale_pos_weight,system_attrs_fixed_params,system_attrs_gp:relative_params:0,state,iter
0,159,0.144223,2026-10-06 02:53:54.336657,2026-10-06 02:55:52.810355,0 days 00:01:58.473698,0.276413,0.011685,0,0.100000,4000,166,1.0,NaN,"{""feature_fraction"": 0.27641343005495034, ""lea...",COMPLETE,160
1,189,0.143950,2026-10-06 03:49:03.750681,2026-10-06 03:50:59.960659,0 days 00:01:56.209978,0.272505,0.011555,0,0.009703,4000,157,1.0,NaN,"{""feature_fraction"": 0.272504623324586, ""learn...",COMPLETE,190
2,100,0.143589,2026-10-06 01:08:00.134036,2026-10-06 01:09:15.912086,0 days 00:01:15.778050,0.363927,0.025000,0,0.006716,2472,158,1.0,NaN,"{""feature_fraction"": 0.36392719749807123, ""lea...",COMPLETE,101
3,192,0.143466,2026-10-06 03:54:22.107306,2026-10-06 03:56:22.735967,0 days 00:02:00.628661,0.308348,0.011828,0,0.044820,4000,167,1.0,NaN,"{""feature_fraction"": 0.3083476155787994, ""lear...",COMPLETE,193
4,191,0.143376,2026-10-06 03:52:27.974870,2026-10-06 03:54:22.075156,0 days 00:01:54.100286,0.253460,0.011467,0,0.075461,4000,154,1.0,NaN,"{""feature_fraction"": 0.25346023723886746, ""lea...",COMPLETE,192

# Producción

## Final training sobre todos los meses de `PARAM["train_final"]`

In [21]:
dataset_final_cpu = (
    df_completo
    .loc[df_completo["foto_mes"].isin(PARAM["train_final"])]
    .to_pandas()
    .reset_index(drop=True)
)
dataset_final_cpu["clase01"] = (
    dataset_final_cpu["ternaria"].isin(["BAJA+1", "BAJA+2"])
    .astype(np.int8)
)

dataset_final_cpu.groupby("ternaria").size()

ternaria
BAJA+1        4000
BAJA+2        4067
continua    645999
dtype: int64

In [22]:
dataset_final_cpu.clase01.value_counts()

clase01
0    645999
1      8067
Name: count, dtype: int64

In [23]:
param_final = {
    **PARAM["lgbm"]["param_fijos"],
    **PARAM["out"]["lgbm"]["mejores_hiperparametros"],
}

num_boost_round_final = int(param_final.pop("num_iterations"))
param_final["min_data_in_leaf"] = round(
    param_final["min_data_in_leaf"] / PARAM["trainingstrategy"]["undersampling"]
)
param_final

{'boosting': 'gbdt',
 'objective': 'binary',
 'metric': 'average_precision',
 'feature_pre_filter': False,
 'first_metric_only': False,
 'boost_from_average': True,
 'force_row_wise': True,
 'deterministic': True,
 'verbosity': -100,
 'seed': 230047,
 'max_depth': -1,
 'min_gain_to_split': 0.0,
 'lambda_l1': 0.0,
 'lambda_l2': 0.0,
 'max_bin': 31,
 'bagging_fraction': 1.0,
 'pos_bagging_fraction': 1.0,
 'neg_bagging_fraction': 1.0,
 'is_unbalance': False,
 'scale_pos_weight': 1.0,
 'drop_rate': 0.1,
 'max_drop': 50,
 'skip_drop': 0.5,
 'extra_trees': False,
 'early_stopping': 0,
 'min_data_in_leaf': 0,
 'feature_fraction': 0.27641343005495034,
 'num_leaves': 166,
 'min_sum_hessian_in_leaf': 0.1,
 'learning_rate': 0.011685329568129043}

In [24]:
print(campos_buenos)

['numero_de_cliente', 'foto_mes', 'active_quarter', 'cliente_vip', 'internet', 'cliente_edad', 'cliente_antiguedad', 'mrentabilidad', 'mrentabilidad_annual', 'mcomisiones', 'mactivos_margen', 'mpasivos_margen', 'cproductos', 'tcuentas', 'ccuenta_corriente', 'mcuenta_corriente_adicional', 'mcuenta_corriente', 'ccaja_ahorro', 'mcaja_ahorro', 'mcaja_ahorro_adicional', 'mcaja_ahorro_dolares', 'cdescubierto_preacordado', 'mcuentas_saldo', 'ctarjeta_debito', 'ctarjeta_debito_transacciones', 'mautoservicio', 'ctarjeta_visa', 'ctarjeta_visa_transacciones', 'mtarjeta_visa_consumo', 'ctarjeta_master', 'ctarjeta_master_transacciones', 'mtarjeta_master_consumo', 'cprestamos_prendarios', 'mprestamos_prendarios', 'cprestamos_hipotecarios', 'mprestamos_hipotecarios', 'cplazo_fijo', 'mplazo_fijo_dolares', 'mplazo_fijo_pesos', 'cinversion1', 'minversion1_pesos', 'minversion1_dolares', 'cinversion2', 'minversion2', 'cseguro_vida', 'cseguro_auto', 'cseguro_vivienda', 'cseguro_accidentes_personales', 'ccaja_seguridad', 'cpayroll_trx', 'mpayroll', 'mpayroll2', 'cpayroll2_trx', 'ccuenta_debitos_automaticos', 'mcuenta_debitos_automaticos', 'ctarjeta_visa_debitos_automaticos', 'mttarjeta_visa_debitos_automaticos', 'ctarjeta_master_debitos_automaticos', 'mttarjeta_master_debitos_automaticos', 'cpagodeservicios', 'mpagodeservicios', 'cpagomiscuentas', 'mpagomiscuentas', 'ccajeros_propios_descuentos', 'mcajeros_propios_descuentos', 'ctarjeta_visa_descuentos', 'mtarjeta_visa_descuentos', 'ctarjeta_master_descuentos', 'mtarjeta_master_descuentos', 'ccomisiones_mantenimiento', 'mcomisiones_mantenimiento', 'ccomisiones_otras', 'mcomisiones_otras', 'cforex', 'cforex_buy', 'mforex_buy', 'cforex_sell', 'mforex_sell', 'ctransferencias_recibidas', 'mtransferencias_recibidas', 'ctransferencias_emitidas', 'mtransferencias_emitidas', 'cextraccion_autoservicio', 'mextraccion_autoservicio', 'ccheques_depositados', 'mcheques_depositados', 'ccheques_emitidos', 'mcheques_emitidos', 'ccheques_depositados_rechazados', 'mcheques_depositados_rechazados', 'ccheques_emitidos_rechazados', 'mcheques_emitidos_rechazados', 'tcallcenter', 'ccallcenter_transacciones', 'thomebanking', 'chomebanking_transacciones', 'ccajas_transacciones', 'ccajas_consultas', 'ccajas_depositos', 'ccajas_extracciones', 'ccajas_otras', 'catm_trx', 'matm', 'catm_trx_other', 'matm_other', 'ctrx_quarter', 'tmobile_app', 'cmobile_app_trx', 'Master_delinquency', 'Master_status', 'Master_mfinanciacion_limite', 'Master_Fvencimiento', 'Master_Finiciomora', 'Master_msaldototal', 'Master_msaldopesos', 'Master_msaldodolares', 'Master_mconsumospesos', 'Master_mconsumosdolares', 'Master_mlimitecompra', 'Master_madelantopesos', 'Master_madelantodolares', 'Master_fultimo_cierre', 'Master_mpagado', 'Master_mpagospesos', 'Master_mpagosdolares', 'Master_fechaalta', 'Master_mconsumototal', 'Master_cconsumos', 'Master_cadelantosefectivo', 'Master_mpagominimo', 'Visa_delinquency', 'Visa_status', 'Visa_mfinanciacion_limite', 'Visa_Fvencimiento', 'Visa_Finiciomora', 'Visa_msaldototal', 'Visa_msaldopesos', 'Visa_msaldodolares', 'Visa_mconsumospesos', 'Visa_mconsumosdolares', 'Visa_mlimitecompra', 'Visa_madelantopesos', 'Visa_madelantodolares', 'Visa_fultimo_cierre', 'Visa_mpagado', 'Visa_mpagospesos', 'Visa_mpagosdolares', 'Visa_fechaalta', 'Visa_mconsumototal', 'Visa_cconsumos', 'Visa_cadelantosefectivo', 'Visa_mpagominimo', 'active_quarter_lag_pond', 'cliente_vip_lag_pond', 'internet_lag_pond', 'cliente_edad_lag_pond', 'cliente_antiguedad_lag_pond', 'mrentabilidad_lag_pond', 'mrentabilidad_annual_lag_pond', 'mcomisiones_lag_pond', 'mactivos_margen_lag_pond', 'mpasivos_margen_lag_pond', 'cproductos_lag_pond', 'tcuentas_lag_pond', 'ccuenta_corriente_lag_pond', 'mcuenta_corriente_adicional_lag_pond', 'mcuenta_corriente_lag_pond', 'ccaja_ahorro_lag_pond', 'mcaja_ahorro_lag_pond', 'mcaja_ahorro_adicional_lag_pond', 'mcaja_ahorro_dolares_lag_pond', 'cdescubierto_preacordado_lag_pond', 'active_quarter_delta_lag_pond', 'cliente_vip_delta_lag_pond', 'internet_delta_lag_pond', 'cliente_edad_delta_lag_pond', 'cliente_antiguedad_delta_lag_pond', 'mrentabilidad_delta_lag_pond', 'mrentabilidad_annual_delta_lag_pond', 'mcomisiones_delta_lag_pond', 'mactivos_margen_delta_lag_pond', 'mpasivos_margen_delta_lag_pond', 'cproductos_delta_lag_pond', 'tcuentas_delta_lag_pond', 'ccuenta_corriente_delta_lag_pond', 'mcuenta_corriente_adicional_delta_lag_pond', 'mcuenta_corriente_delta_lag_pond', 'ccaja_ahorro_delta_lag_pond', 'mcaja_ahorro_delta_lag_pond', 'mcaja_ahorro_adicional_delta_lag_pond', 'mcaja_ahorro_dolares_delta_lag_pond', 'cdescubierto_preacordado_delta_lag_pond', 'mcuentas_saldo_lag_pond', 'ctarjeta_debito_lag_pond', 'ctarjeta_debito_transacciones_lag_pond', 'mautoservicio_lag_pond', 'ctarjeta_visa_lag_pond', 'ctarjeta_visa_transacciones_lag_pond', 'mtarjeta_visa_consumo_lag_pond', 'ctarjeta_master_lag_pond', 'ctarjeta_master_transacciones_lag_pond', 'mtarjeta_master_consumo_lag_pond', 'cprestamos_personales_lag_pond', 'mprestamos_personales_lag_pond', 'cprestamos_prendarios_lag_pond', 'mprestamos_prendarios_lag_pond', 'cprestamos_hipotecarios_lag_pond', 'mprestamos_hipotecarios_lag_pond', 'cplazo_fijo_lag_pond', 'mplazo_fijo_dolares_lag_pond', 'mplazo_fijo_pesos_lag_pond', 'cinversion1_lag_pond', 'mcuentas_saldo_delta_lag_pond', 'ctarjeta_debito_delta_lag_pond', 'ctarjeta_debito_transacciones_delta_lag_pond', 'mautoservicio_delta_lag_pond', 'ctarjeta_visa_delta_lag_pond', 'ctarjeta_visa_transacciones_delta_lag_pond', 'mtarjeta_visa_consumo_delta_lag_pond', 'ctarjeta_master_delta_lag_pond', 'ctarjeta_master_transacciones_delta_lag_pond', 'mtarjeta_master_consumo_delta_lag_pond', 'cprestamos_personales_delta_lag_pond', 'mprestamos_personales_delta_lag_pond', 'cprestamos_prendarios_delta_lag_pond', 'mprestamos_prendarios_delta_lag_pond', 'cprestamos_hipotecarios_delta_lag_pond', 'mprestamos_hipotecarios_delta_lag_pond', 'cplazo_fijo_delta_lag_pond', 'mplazo_fijo_dolares_delta_lag_pond', 'mplazo_fijo_pesos_delta_lag_pond', 'cinversion1_delta_lag_pond', 'minversion1_pesos_lag_pond', 'minversion1_dolares_lag_pond', 'cinversion2_lag_pond', 'minversion2_lag_pond', 'cseguro_vida_lag_pond', 'cseguro_auto_lag_pond', 'cseguro_vivienda_lag_pond', 'cseguro_accidentes_personales_lag_pond', 'ccaja_seguridad_lag_pond', 'cpayroll_trx_lag_pond', 'mpayroll_lag_pond', 'mpayroll2_lag_pond', 'cpayroll2_trx_lag_pond', 'ccuenta_debitos_automaticos_lag_pond', 'mcuenta_debitos_automaticos_lag_pond', 'ctarjeta_visa_debitos_automaticos_lag_pond', 'mttarjeta_visa_debitos_automaticos_lag_pond', 'ctarjeta_master_debitos_automaticos_lag_pond', 'mttarjeta_master_debitos_automaticos_lag_pond', 'cpagodeservicios_lag_pond', 'minversion1_pesos_delta_lag_pond', 'minversion1_dolares_delta_lag_pond', 'cinversion2_delta_lag_pond', 'minversion2_delta_lag_pond', 'cseguro_vida_delta_lag_pond', 'cseguro_auto_delta_lag_pond', 'cseguro_vivienda_delta_lag_pond', 'cseguro_accidentes_personales_delta_lag_pond', 'ccaja_seguridad_delta_lag_pond', 'cpayroll_trx_delta_lag_pond', 'mpayroll_delta_lag_pond', 'mpayroll2_delta_lag_pond', 'cpayroll2_trx_delta_lag_pond', 'ccuenta_debitos_automaticos_delta_lag_pond', 'mcuenta_debitos_automaticos_delta_lag_pond', 'ctarjeta_visa_debitos_automaticos_delta_lag_pond', 'mttarjeta_visa_debitos_automaticos_delta_lag_pond', 'ctarjeta_master_debitos_automaticos_delta_lag_pond', 'mttarjeta_master_debitos_automaticos_delta_lag_pond', 'cpagodeservicios_delta_lag_pond', 'mpagodeservicios_lag_pond', 'cpagomiscuentas_lag_pond', 'mpagomiscuentas_lag_pond', 'ccajeros_propios_descuentos_lag_pond', 'mcajeros_propios_descuentos_lag_pond', 'ctarjeta_visa_descuentos_lag_pond', 'mtarjeta_visa_descuentos_lag_pond', 'ctarjeta_master_descuentos_lag_pond', 'mtarjeta_master_descuentos_lag_pond', 'ccomisiones_mantenimiento_lag_pond', 'mcomisiones_mantenimiento_lag_pond', 'ccomisiones_otras_lag_pond', 'mcomisiones_otras_lag_pond', 'cforex_lag_pond', 'cforex_buy_lag_pond', 'mforex_buy_lag_pond', 'cforex_sell_lag_pond', 'mforex_sell_lag_pond', 'ctransferencias_recibidas_lag_pond', 'mtransferencias_recibidas_lag_pond', 'mpagodeservicios_delta_lag_pond', 'cpagomiscuentas_delta_lag_pond', 'mpagomiscuentas_delta_lag_pond', 'ccajeros_propios_descuentos_delta_lag_pond', 'mcajeros_propios_descuentos_delta_lag_pond', 'ctarjeta_visa_descuentos_delta_lag_pond', 'mtarjeta_visa_descuentos_delta_lag_pond', 'ctarjeta_master_descuentos_delta_lag_pond', 'mtarjeta_master_descuentos_delta_lag_pond', 'ccomisiones_mantenimiento_delta_lag_pond', 'mcomisiones_mantenimiento_delta_lag_pond', 'ccomisiones_otras_delta_lag_pond', 'mcomisiones_otras_delta_lag_pond', 'cforex_delta_lag_pond', 'cforex_buy_delta_lag_pond', 'mforex_buy_delta_lag_pond', 'cforex_sell_delta_lag_pond', 'mforex_sell_delta_lag_pond', 'ctransferencias_recibidas_delta_lag_pond', 'mtransferencias_recibidas_delta_lag_pond', 'ctransferencias_emitidas_lag_pond', 'mtransferencias_emitidas_lag_pond', 'cextraccion_autoservicio_lag_pond', 'mextraccion_autoservicio_lag_pond', 'ccheques_depositados_lag_pond', 'mcheques_depositados_lag_pond', 'ccheques_emitidos_lag_pond', 'mcheques_emitidos_lag_pond', 'ccheques_depositados_rechazados_lag_pond', 'mcheques_depositados_rechazados_lag_pond', 'ccheques_emitidos_rechazados_lag_pond', 'mcheques_emitidos_rechazados_lag_pond', 'tcallcenter_lag_pond', 'ccallcenter_transacciones_lag_pond', 'thomebanking_lag_pond', 'chomebanking_transacciones_lag_pond', 'ccajas_transacciones_lag_pond', 'ccajas_consultas_lag_pond', 'ccajas_depositos_lag_pond', 'ccajas_extracciones_lag_pond', 'ctransferencias_emitidas_delta_lag_pond', 'mtransferencias_emitidas_delta_lag_pond', 'cextraccion_autoservicio_delta_lag_pond', 'mextraccion_autoservicio_delta_lag_pond', 'ccheques_depositados_delta_lag_pond', 'mcheques_depositados_delta_lag_pond', 'ccheques_emitidos_delta_lag_pond', 'mcheques_emitidos_delta_lag_pond', 'ccheques_depositados_rechazados_delta_lag_pond', 'mcheques_depositados_rechazados_delta_lag_pond', 'ccheques_emitidos_rechazados_delta_lag_pond', 'mcheques_emitidos_rechazados_delta_lag_pond', 'tcallcenter_delta_lag_pond', 'ccallcenter_transacciones_delta_lag_pond', 'thomebanking_delta_lag_pond', 'chomebanking_transacciones_delta_lag_pond', 'ccajas_transacciones_delta_lag_pond', 'ccajas_consultas_delta_lag_pond', 'ccajas_depositos_delta_lag_pond', 'ccajas_extracciones_delta_lag_pond', 'ccajas_otras_lag_pond', 'catm_trx_lag_pond', 'matm_lag_pond', 'catm_trx_other_lag_pond', 'matm_other_lag_pond', 'ctrx_quarter_lag_pond', 'tmobile_app_lag_pond', 'cmobile_app_trx_lag_pond', 'Master_delinquency_lag_pond', 'Master_status_lag_pond', 'Master_mfinanciacion_limite_lag_pond', 'Master_Fvencimiento_lag_pond', 'Master_Finiciomora_lag_pond', 'Master_msaldototal_lag_pond', 'Master_msaldopesos_lag_pond', 'Master_msaldodolares_lag_pond', 'Master_mconsumospesos_lag_pond', 'Master_mconsumosdolares_lag_pond', 'Master_mlimitecompra_lag_pond', 'Master_madelantopesos_lag_pond', 'ccajas_otras_delta_lag_pond', 'catm_trx_delta_lag_pond', 'matm_delta_lag_pond', 'catm_trx_other_delta_lag_pond', 'matm_other_delta_lag_pond', 'ctrx_quarter_delta_lag_pond', 'tmobile_app_delta_lag_pond', 'cmobile_app_trx_delta_lag_pond', 'Master_delinquency_delta_lag_pond', 'Master_status_delta_lag_pond', 'Master_mfinanciacion_limite_delta_lag_pond', 'Master_Fvencimiento_delta_lag_pond', 'Master_Finiciomora_delta_lag_pond', 'Master_msaldototal_delta_lag_pond', 'Master_msaldopesos_delta_lag_pond', 'Master_msaldodolares_delta_lag_pond', 'Master_mconsumospesos_delta_lag_pond', 'Master_mconsumosdolares_delta_lag_pond', 'Master_mlimitecompra_delta_lag_pond', 'Master_madelantopesos_delta_lag_pond', 'Master_madelantodolares_lag_pond', 'Master_fultimo_cierre_lag_pond', 'Master_mpagado_lag_pond', 'Master_mpagospesos_lag_pond', 'Master_mpagosdolares_lag_pond', 'Master_fechaalta_lag_pond', 'Master_mconsumototal_lag_pond', 'Master_cconsumos_lag_pond', 'Master_cadelantosefectivo_lag_pond', 'Master_mpagominimo_lag_pond', 'Visa_delinquency_lag_pond', 'Visa_status_lag_pond', 'Visa_mfinanciacion_limite_lag_pond', 'Visa_Fvencimiento_lag_pond', 'Visa_Finiciomora_lag_pond', 'Visa_msaldototal_lag_pond', 'Visa_msaldopesos_lag_pond', 'Visa_msaldodolares_lag_pond', 'Visa_mconsumospesos_lag_pond', 'Visa_mconsumosdolares_lag_pond', 'Master_madelantodolares_delta_lag_pond', 'Master_fultimo_cierre_delta_lag_pond', 'Master_mpagado_delta_lag_pond', 'Master_mpagospesos_delta_lag_pond', 'Master_mpagosdolares_delta_lag_pond', 'Master_fechaalta_delta_lag_pond', 'Master_mconsumototal_delta_lag_pond', 'Master_cconsumos_delta_lag_pond', 'Master_cadelantosefectivo_delta_lag_pond', 'Master_mpagominimo_delta_lag_pond', 'Visa_delinquency_delta_lag_pond', 'Visa_status_delta_lag_pond', 'Visa_mfinanciacion_limite_delta_lag_pond', 'Visa_Fvencimiento_delta_lag_pond', 'Visa_Finiciomora_delta_lag_pond', 'Visa_msaldototal_delta_lag_pond', 'Visa_msaldopesos_delta_lag_pond', 'Visa_msaldodolares_delta_lag_pond', 'Visa_mconsumospesos_delta_lag_pond', 'Visa_mconsumosdolares_delta_lag_pond', 'Visa_mlimitecompra_lag_pond', 'Visa_madelantopesos_lag_pond', 'Visa_madelantodolares_lag_pond', 'Visa_fultimo_cierre_lag_pond', 'Visa_mpagado_lag_pond', 'Visa_mpagospesos_lag_pond', 'Visa_mpagosdolares_lag_pond', 'Visa_fechaalta_lag_pond', 'Visa_mconsumototal_lag_pond', 'Visa_cconsumos_lag_pond', 'Visa_cadelantosefectivo_lag_pond', 'Visa_mpagominimo_lag_pond', 'Visa_mlimitecompra_delta_lag_pond', 'Visa_madelantopesos_delta_lag_pond', 'Visa_madelantodolares_delta_lag_pond', 'Visa_fultimo_cierre_delta_lag_pond', 'Visa_mpagado_delta_lag_pond', 'Visa_mpagospesos_delta_lag_pond', 'Visa_mpagosdolares_delta_lag_pond', 'Visa_fechaalta_delta_lag_pond', 'Visa_mconsumototal_delta_lag_pond', 'Visa_cconsumos_delta_lag_pond', 'Visa_cadelantosefectivo_delta_lag_pond', 'Visa_mpagominimo_delta_lag_pond']

In [25]:
dtrain_final = lgb.Dataset(
    data=dataset_final_cpu[campos_buenos],
    label=dataset_final_cpu["clase01"],
    feature_name=campos_buenos,
)

modelo_final = lgb.train(
    params=param_final,
    train_set=dtrain_final,
    num_boost_round=num_boost_round_final,
)

## Importancia de variables y modelo

In [26]:
arboles_df = modelo_final.trees_to_dataframe()
splits_df = arboles_df.loc[arboles_df["split_feature"].notna()]

tb_importancia = (
    splits_df
    .groupby("split_feature", as_index=False)
    .agg(
        Gain=("split_gain", "sum"),
        Cover=("count", "sum"),
        Frequency=("split_feature", "size"),
    )
    .rename(columns={"split_feature": "Feature"})
)

for columna in ["Gain", "Cover", "Frequency"]:
    total = tb_importancia[columna].sum()
    if total > 0:
        tb_importancia[columna] = tb_importancia[columna] / total

tb_importancia = tb_importancia.sort_values("Gain", ascending=False)
tb_importancia.to_csv(
    os.path.join(EXPERIMENT_URL, "impo.txt"),
    sep="\t",
    index=False,
)
modelo_final.save_model(os.path.join(EXPERIMENT_URL, "modelo.txt"))

tb_importancia.head(20)

                            Feature      Gain     Cover  Frequency
302                    ctrx_quarter  0.044971  0.008782   0.009623
321                    mcaja_ahorro  0.038035  0.006863   0.009017
393                        mpayroll  0.025125  0.012698   0.002436
363                  mcuentas_saldo  0.024996  0.012685   0.011276
425           mtarjeta_visa_consumo  0.024950  0.003898   0.004353
237                    cpayroll_trx  0.024669  0.006266   0.001368
293     ctarjeta_visa_transacciones  0.017842  0.004333   0.005036
414            mrentabilidad_annual  0.015582  0.017496   0.015442
354               mcuenta_corriente  0.015533  0.009716   0.013152
269   ctarjeta_debito_transacciones  0.014901  0.002272   0.003826
304           ctrx_quarter_lag_pond  0.013096  0.003048   0.005123
390                 mpasivos_margen  0.012908  0.004496   0.010483
219                    cliente_edad  0.011687  0.010349   0.018455
111                Visa_mpagominimo  0.010885  0.003929   0.006953
443               numero_de_cliente  0.010089  0.006712   0.018653
3               Master_Fvencimiento  0.009727  0.006767   0.014371
409  mprestamos_personales_lag_pond  0.009526  0.013206   0.004414
309                 mactivos_margen  0.009364  0.011986   0.012215
413                   mrentabilidad  0.009203  0.005838   0.012786
318                   mautoservicio  0.008893  0.005132   0.004189

## Scoring de julio

In [27]:
df_completo.shape

(983061, 459)

In [28]:
dfuture_cpu = (
    df_completo
    .loc[df_completo["foto_mes"].isin(PARAM["future"])]
    .to_pandas()
    .reset_index(drop=True)
)

prediccion = modelo_final.predict(dfuture_cpu[campos_buenos])

tb_prediccion = dfuture_cpu[["numero_de_cliente", "foto_mes", "ternaria"]].copy()
tb_prediccion["prob"] = prediccion
# Estas probabilidades se guardan en la carpeta de la segunda BO.


tb_prediccion.head()

   numero_de_cliente  foto_mes ternaria      prob
0           12159854    202107      NaN  0.000115
1           12159858    202107      NaN  0.000417
2           12160484    202107      NaN  0.000160
3           12160591    202107      NaN  0.000007
4           12160747    202107      NaN  0.000388

## Documentación de la primera BO

In [29]:
contenido_md = [
    f"# Resumen — {experiment_name}",
    "",
    "- Etiquetas de entrenamiento y validación: reales.",
    "- Validación: todas las filas de marzo a junio con training == 0, como en la notebook base.",
    "- Julio no tiene BAJA+2 real: no se calcula ganancia sobre ese mes.",
    f"- Registros de entrenamiento BO: {len(X_train_bo)}",
    f"- Registros de validación BO: {len(X_validate_bo)}",
    f"- Registros de entrenamiento final: {len(dataset_final_cpu)}",
    f"- Registros predichos: {len(dfuture_cpu)}",
    f"- Probabilidades de julio: se guardan en `{experimento_segunda}/predicciones_julio/prediccion.txt`.",
    f"- Dataset: `{dataset_file}`",
    f"- Meses de entrenamiento: {', '.join(map(str, PARAM['train']))}",
    f"- Meses de entrenamiento final: {', '.join(map(str, PARAM['train_final']))}",
    f"- Meses a predecir: {', '.join(map(str, PARAM['future']))}",
    f"- Semilla: {PARAM['semilla_primigenia']}",
    "- Clase positiva: BAJA+1 y BAJA+2.",
    f"- Columnas excluidas: {', '.join(sorted(columnas_excluidas))}",
    f"- Porcentaje para entrenamiento en el split: {PARAM['training_pct']}",
    f"- Undersampling: {PARAM['trainingstrategy']['undersampling']}",
    f"- Corridas por BO: {PARAM['hyperparametertuning']['iteraciones']}",
    f"- Inicializaciones totales: {PARAM['hyperparametertuning']['n_startup_trials']}",
    f"- Inicializaciones desde RDS: {len(puntos_iniciales_bo)}",
    f"- Inicializaciones aleatorias: {PARAM['hyperparametertuning']['n_startup_trials'] - len(puntos_iniciales_bo)}",
    f"- Fuente de las inicializaciones: `{archivo_validaciones}`",
    f"- IDs de validación usados: {', '.join(map(str, modelos_iniciales['id_validacion']))}",
    "- Selección: mayor ganancia dentro del dataset actual; se completa con los demás datasets.",
    "- min_data_in_leaf de los RDS: se revierte el ajuste por undersampling antes de inicializar.",
    f"- Rangos de HP: `{rangos_bo}`",
    f"- Mejor trial de Optuna: {study.best_trial.number}",
    f"- Mejor Average Precision: {PARAM['out']['lgbm']['y']}",
    f"- Mejores HP: `{PARAM['out']['lgbm']['mejores_hiperparametros']}`",
]
with open(os.path.join(EXPERIMENT_URL, "resumen.md"), "w", encoding="utf-8") as archivo:
    archivo.write("\n".join(contenido_md) + "\n")

## Segunda BO: incorpora julio al entrenamiento y optimiza `prob_corte`

In [30]:
experimento_origen = experiment_name
meses_reales = PARAM["train"].copy()
meses_julio = PARAM["future"].copy()
dataset_julio_cpu = dfuture_cpu.copy()
prob_julio = prediccion.copy()
baja1_julio = dataset_julio_cpu["ternaria"].isin(["BAJA+1"]).to_numpy()

# Los BAJA+1 reales se conservan; el corte asigna BAJA+2 al resto.
def etiquetar_julio(prob_corte):
    return np.where(
        baja1_julio,
        "BAJA+1",
        np.where(prob_julio >= prob_corte, "BAJA+2", "CONTINUA"),
    )

# El rango se obtiene de los puestos definidos por PARAM["cortes"].
probabilidades_ordenadas = np.sort(prob_julio[~baja1_julio])[::-1]
rangos_bo["prob_corte"] = (
    float(probabilidades_ordenadas[max(PARAM["cortes"]) - 1]),
    float(probabilidades_ordenadas[min(PARAM["cortes"]) - 1]),
)

experiment_name = experimento_segunda
EXPERIMENT_URL = os.path.join(EXP_URL, experiment_name)
os.makedirs(EXPERIMENT_URL, exist_ok=True)
PARAM["experimento"] = experiment_name
PARAM["train"] = meses_reales + meses_julio
PARAM["train_final"] = PARAM["train"].copy()
PARAM["future"] = future_segunda.copy()
PARAM["out"]["lgbm"] = {}

carpeta_predicciones_julio = os.path.join(EXPERIMENT_URL, "predicciones_julio")
os.makedirs(carpeta_predicciones_julio, exist_ok=True)
dataset_julio_cpu[["numero_de_cliente", "foto_mes"]].assign(prob=prob_julio).to_csv(
    os.path.join(carpeta_predicciones_julio, "prediccion.txt"),
    sep="\t",
    index=False,
)

# Se mantiene la partición real de la primera BO. Julio no entra en dvalidate.
# El azar de undersampling de julio permanece fijo al variar prob_corte.
rng = np.random.default_rng(PARAM["semilla_primigenia"])
azar_julio = rng.random(len(dataset_julio_cpu))

print("Rango de prob_corte:", rangos_bo["prob_corte"])
print("Meses de validación:", meses_reales)

Rango de prob_corte: (0.0035446538114082874, 0.008646300221991301)
Meses de validación: [202103, 202104, 202105, 202106]

## Estudio Optuna y reanudación

In [31]:
n_startup_trials = PARAM["hyperparametertuning"]["n_startup_trials"]
n_trials_total = PARAM["hyperparametertuning"]["iteraciones"]

sampler = GPSampler(
    seed=PARAM["semilla_primigenia"],
    n_startup_trials=n_startup_trials,
    deterministic_objective=False,
)

study_db_url = os.path.join(EXPERIMENT_URL, "optuna_study.db")
storage_url = f"sqlite:///{study_db_url}"

study = optuna.create_study(
    study_name=experiment_name,
    direction="maximize",
    sampler=sampler,
    storage=storage_url,
    load_if_exists=True,
)

# Se encolan solamente al crear el estudio; conserva también HP repetidos.
if not study.trials:
    for punto in puntos_iniciales_bo:
        study.enqueue_trial(punto)

/tmp/ipykernel_397057/96132893.py:4: ExperimentalWarning: GPSampler is experimental (supported from v3.6.0). The interface can change in the future.
  sampler = GPSampler(
[I 2026-10-06 04:17:51,229] A new study created in RDB with name: LAG-PSEUDO-001

In [32]:
trials_completos = sum(
    trial.state == TrialState.COMPLETE
    for trial in study.trials
)
trials_restantes = max(0, n_trials_total - trials_completos)

print("Trials completos:", trials_completos)
print("Trials restantes:", trials_restantes)

if trials_restantes > 0:
    study.optimize(
        objective,
        n_trials=trials_restantes,
        show_progress_bar=True,
    )
else:
    print("c'est fini")

Trials completos: 0
Trials restantes: 200

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-10-06 04:18:09,640] Trial 0 finished with value: 0.11968225466366741 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5, 'prob_corte': 0.004017753422711737}. Best is trial 0 with value: 0.11968225466366741.
[I 2026-10-06 04:18:26,994] Trial 1 finished with value: 0.12165313532584009 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5, 'prob_corte': 0.0058642247881834355}. Best is trial 1 with value: 0.12165313532584009.
[I 2026-10-06 04:18:44,316] Trial 2 finished with value: 0.12164201981796191 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5, 'prob_corte': 0.007025422539945814}. Best is trial 1 with value: 0.12165313532584009.
[I 2026-10-06 04:19:38,565] Trial 3 finished with value: 0.12681825710804445 and parameters: {'num_iterations': 1067, 'num_leaves': 2048, 'feature_fraction': 0.35, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00675493259696748, 'min_data_in_leaf': 168, 'scale_pos_weight': 0.5, 'prob_corte': 0.0038224187305656177}. Best is trial 3 with value: 0.12681825710804445.
[I 2026-10-06 04:20:31,698] Trial 4 finished with value: 0.12671824728790007 and parameters: {'num_iterations': 1067, 'num_leaves': 2048, 'feature_fraction': 0.35, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00675493259696748, 'min_data_in_leaf': 168, 'scale_pos_weight': 0.5, 'prob_corte': 0.007484388666659462}. Best is trial 3 with value: 0.12681825710804445.
[I 2026-10-06 04:20:49,008] Trial 5 finished with value: 0.12308878998099658 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5, 'prob_corte': 0.006722248382082383}. Best is trial 3 with value: 0.12681825710804445.
[I 2026-10-06 04:21:43,268] Trial 6 finished with value: 0.12556577048096132 and parameters: {'num_iterations': 1067, 'num_leaves': 2048, 'feature_fraction': 0.35, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00675493259696748, 'min_data_in_leaf': 168, 'scale_pos_weight': 0.5, 'prob_corte': 0.00377385684034839}. Best is trial 3 with value: 0.12681825710804445.
[I 2026-10-06 04:22:29,290] Trial 7 finished with value: 0.10990470231927285 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1, 'prob_corte': 0.007162918857743016}. Best is trial 3 with value: 0.12681825710804445.
[I 2026-10-06 04:23:15,043] Trial 8 finished with value: 0.10994097232224513 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1, 'prob_corte': 0.006736981905854126}. Best is trial 3 with value: 0.12681825710804445.
[I 2026-10-06 04:24:00,872] Trial 9 finished with value: 0.1099691572353116 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1, 'prob_corte': 0.008280486412380371}. Best is trial 3 with value: 0.12681825710804445.
[I 2026-10-06 04:24:46,923] Trial 10 finished with value: 0.11006168189300806 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1, 'prob_corte': 0.00603365257016765}. Best is trial 3 with value: 0.12681825710804445.
[I 2026-10-06 04:25:07,298] Trial 11 finished with value: 0.1269863270962039 and parameters: {'num_iterations': 454, 'num_leaves': 256, 'feature_fraction': 0.264156247389931, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0185711199192682, 'min_data_in_leaf': 181, 'scale_pos_weight': 0.5, 'prob_corte': 0.006498551955657724}. Best is trial 11 with value: 0.1269863270962039.
[I 2026-10-06 04:25:41,308] Trial 12 finished with value: 0.10875176675678762 and parameters: {'num_iterations': 1345, 'num_leaves': 43, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00276306526156717, 'min_data_in_leaf': 52, 'scale_pos_weight': 1, 'prob_corte': 0.005893129988326288}. Best is trial 11 with value: 0.1269863270962039.
[I 2026-10-06 04:26:00,753] Trial 13 finished with value: 0.10179701600592542 and parameters: {'num_iterations': 611, 'num_leaves': 20, 'feature_fraction': 0.552791861343054, 'min_sum_hessian_in_leaf': 0.0377107584841935, 'learning_rate': 0.01, 'min_data_in_leaf': 0, 'scale_pos_weight': 1, 'prob_corte': 0.004866573887492603}. Best is trial 11 with value: 0.1269863270962039.
[I 2026-10-06 04:26:46,860] Trial 14 finished with value: 0.10995051159836805 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1, 'prob_corte': 0.007516093140869866}. Best is trial 11 with value: 0.1269863270962039.
[I 2026-10-06 04:27:32,894] Trial 15 finished with value: 0.10994443906894914 and parameters: {'num_iterations': 1805, 'num_leaves': 44, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00230449723537581, 'min_data_in_leaf': 73, 'scale_pos_weight': 1, 'prob_corte': 0.006258333547988694}. Best is trial 11 with value: 0.1269863270962039.

/home/marco/anaconda3/envs/cmeyf-cuda13/lib/python3.11/site-packages/optuna/trial/_trial.py:664: UserWarning: Fixed parameter min_sum_hessian_in_leaf with value 1e-06 is out of range for distribution FloatDistribution(high=0.1, log=True, low=0.0001, step=None).
  optuna_warn(

[I 2026-10-06 04:28:31,100] Trial 16 finished with value: 0.10439645228040688 and parameters: {'num_iterations': 2152, 'num_leaves': 16, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 1e-06, 'learning_rate': 0.004, 'min_data_in_leaf': 0, 'scale_pos_weight': 1, 'prob_corte': 0.006980912410206179}. Best is trial 11 with value: 0.1269863270962039.

/home/marco/anaconda3/envs/cmeyf-cuda13/lib/python3.11/site-packages/optuna/trial/_trial.py:664: UserWarning: Fixed parameter min_sum_hessian_in_leaf with value 1e-06 is out of range for distribution FloatDistribution(high=0.1, log=True, low=0.0001, step=None).
  optuna_warn(

[I 2026-10-06 04:29:49,070] Trial 17 finished with value: 0.10571362154371747 and parameters: {'num_iterations': 2837, 'num_leaves': 16, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 1e-06, 'learning_rate': 0.004, 'min_data_in_leaf': 0, 'scale_pos_weight': 1, 'prob_corte': 0.0035658114802606627}. Best is trial 11 with value: 0.1269863270962039.

/home/marco/anaconda3/envs/cmeyf-cuda13/lib/python3.11/site-packages/optuna/trial/_trial.py:664: UserWarning: Fixed parameter min_sum_hessian_in_leaf with value 1e-06 is out of range for distribution FloatDistribution(high=0.1, log=True, low=0.0001, step=None).
  optuna_warn(

[I 2026-10-06 04:30:14,037] Trial 18 finished with value: 0.11931078435342186 and parameters: {'num_iterations': 712, 'num_leaves': 86, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 1e-06, 'learning_rate': 0.00757969257611117, 'min_data_in_leaf': 0, 'scale_pos_weight': 1, 'prob_corte': 0.006810223898698845}. Best is trial 11 with value: 0.1269863270962039.
[I 2026-10-06 04:30:33,536] Trial 19 finished with value: 0.1005513414973785 and parameters: {'num_iterations': 611, 'num_leaves': 20, 'feature_fraction': 0.552791861343054, 'min_sum_hessian_in_leaf': 0.0377107584841935, 'learning_rate': 0.01, 'min_data_in_leaf': 0, 'scale_pos_weight': 1, 'prob_corte': 0.004731371489105197}. Best is trial 11 with value: 0.1269863270962039.
[I 2026-10-06 04:31:01,500] Trial 20 finished with value: 0.12429003831774788 and parameters: {'num_iterations': 715, 'num_leaves': 164, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.006, 'min_data_in_leaf': 0, 'scale_pos_weight': 1, 'prob_corte': 0.008574781647926749}. Best is trial 11 with value: 0.1269863270962039.

/home/marco/anaconda3/envs/cmeyf-cuda13/lib/python3.11/site-packages/optuna/trial/_trial.py:664: UserWarning: Fixed parameter min_sum_hessian_in_leaf with value 1e-06 is out of range for distribution FloatDistribution(high=0.1, log=True, low=0.0001, step=None).
  optuna_warn(

[I 2026-10-06 04:31:26,668] Trial 21 finished with value: 0.11838984982207891 and parameters: {'num_iterations': 712, 'num_leaves': 86, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 1e-06, 'learning_rate': 0.00757969257611117, 'min_data_in_leaf': 0, 'scale_pos_weight': 1, 'prob_corte': 0.005167078984177872}. Best is trial 11 with value: 0.1269863270962039.

/home/marco/anaconda3/envs/cmeyf-cuda13/lib/python3.11/site-packages/optuna/trial/_trial.py:664: UserWarning: Fixed parameter min_sum_hessian_in_leaf with value 1e-06 is out of range for distribution FloatDistribution(high=0.1, log=True, low=0.0001, step=None).
  optuna_warn(

[I 2026-10-06 04:31:51,806] Trial 22 finished with value: 0.11926476068939489 and parameters: {'num_iterations': 712, 'num_leaves': 86, 'feature_fraction': 0.4, 'min_sum_hessian_in_leaf': 1e-06, 'learning_rate': 0.00757969257611117, 'min_data_in_leaf': 0, 'scale_pos_weight': 1, 'prob_corte': 0.006351497950491821}. Best is trial 11 with value: 0.1269863270962039.
[I 2026-10-06 04:33:12,420] Trial 23 finished with value: 0.13938145899476917 and parameters: {'num_iterations': 2140, 'num_leaves': 133, 'feature_fraction': 0.536030890639101, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.02, 'min_data_in_leaf': 0, 'scale_pos_weight': 1, 'prob_corte': 0.0047944533654560905}. Best is trial 23 with value: 0.13938145899476917.
[I 2026-10-06 04:34:33,829] Trial 24 finished with value: 0.13943876215731632 and parameters: {'num_iterations': 2140, 'num_leaves': 133, 'feature_fraction': 0.536030890639101, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.02, 'min_data_in_leaf': 0, 'scale_pos_weight': 1, 'prob_corte': 0.0035719325668388444}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:35:27,412] Trial 25 finished with value: 0.12768641987038074 and parameters: {'num_iterations': 1067, 'num_leaves': 2048, 'feature_fraction': 0.35, 'min_sum_hessian_in_leaf': 0.0001, 'learning_rate': 0.00675493259696748, 'min_data_in_leaf': 168, 'scale_pos_weight': 0.5, 'prob_corte': 0.005927201249860007}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:35:47,869] Trial 26 finished with value: 0.12528388567114282 and parameters: {'num_iterations': 454, 'num_leaves': 256, 'feature_fraction': 0.264156247389931, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0185711199192682, 'min_data_in_leaf': 181, 'scale_pos_weight': 0.5, 'prob_corte': 0.008175992390236529}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:36:05,505] Trial 27 finished with value: 0.12307113446290768 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5, 'prob_corte': 0.007180941347270168}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:36:23,001] Trial 28 finished with value: 0.12193099325222174 and parameters: {'num_iterations': 400, 'num_leaves': 256, 'feature_fraction': 0.239049018582973, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0152796385349906, 'min_data_in_leaf': 137, 'scale_pos_weight': 0.5, 'prob_corte': 0.005597638413170474}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:36:42,400] Trial 29 finished with value: 0.10124460159808522 and parameters: {'num_iterations': 611, 'num_leaves': 20, 'feature_fraction': 0.552791861343054, 'min_sum_hessian_in_leaf': 0.0377107584841935, 'learning_rate': 0.01, 'min_data_in_leaf': 0, 'scale_pos_weight': 1, 'prob_corte': 0.005620037928307153}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:37:13,647] Trial 30 finished with value: 0.08981501511236992 and parameters: {'num_iterations': 1425, 'num_leaves': 20, 'feature_fraction': 0.7208217561747412, 'min_sum_hessian_in_leaf': 0.0008333474321628226, 'learning_rate': 0.0024143185499451952, 'min_data_in_leaf': 41, 'scale_pos_weight': 0.8383837923497148, 'prob_corte': 0.003739022006541323}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:37:46,597] Trial 31 finished with value: 0.10927549366565496 and parameters: {'num_iterations': 982, 'num_leaves': 384, 'feature_fraction': 0.7481248240572645, 'min_sum_hessian_in_leaf': 0.03579114285862779, 'learning_rate': 0.006971955709668485, 'min_data_in_leaf': 872, 'scale_pos_weight': 0.6854945672244066, 'prob_corte': 0.00640086077555431}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:38:49,643] Trial 32 finished with value: 0.11539306768077918 and parameters: {'num_iterations': 2525, 'num_leaves': 27, 'feature_fraction': 0.11750055056600403, 'min_sum_hessian_in_leaf': 0.009011478701480238, 'learning_rate': 0.010811697571961019, 'min_data_in_leaf': 710, 'scale_pos_weight': 0.7024980984989453, 'prob_corte': 0.007994509901423948}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:40:30,435] Trial 33 finished with value: 0.12814099888466599 and parameters: {'num_iterations': 2877, 'num_leaves': 102, 'feature_fraction': 0.6605679584851463, 'min_sum_hessian_in_leaf': 0.0003537880528921333, 'learning_rate': 0.004087795314100894, 'min_data_in_leaf': 254, 'scale_pos_weight': 0.8252056364438936, 'prob_corte': 0.004878760299650616}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:42:51,344] Trial 34 finished with value: 0.1377661821549164 and parameters: {'num_iterations': 2841, 'num_leaves': 363, 'feature_fraction': 0.44516472379563754, 'min_sum_hessian_in_leaf': 0.012631445844554081, 'learning_rate': 0.012477033563107106, 'min_data_in_leaf': 62, 'scale_pos_weight': 0.5757209006965256, 'prob_corte': 0.004822529920794563}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:45:04,611] Trial 35 finished with value: 0.12165497426119283 and parameters: {'num_iterations': 3882, 'num_leaves': 1583, 'feature_fraction': 0.44584784048181647, 'min_sum_hessian_in_leaf': 0.00017845743197516685, 'learning_rate': 0.00706629849097512, 'min_data_in_leaf': 894, 'scale_pos_weight': 0.5776244558851937, 'prob_corte': 0.006747861412518187}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:45:33,163] Trial 36 finished with value: 0.10349698734619497 and parameters: {'num_iterations': 636, 'num_leaves': 628, 'feature_fraction': 0.13240623450643013, 'min_sum_hessian_in_leaf': 0.0016822221952963565, 'learning_rate': 0.004315973005335513, 'min_data_in_leaf': 0, 'scale_pos_weight': 0.5509212314304117, 'prob_corte': 0.00630774192045801}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:47:36,496] Trial 37 finished with value: 0.12697861990350592 and parameters: {'num_iterations': 2870, 'num_leaves': 232, 'feature_fraction': 0.7174415144453733, 'min_sum_hessian_in_leaf': 0.00798804762934227, 'learning_rate': 0.003169973891101593, 'min_data_in_leaf': 353, 'scale_pos_weight': 0.5607928573323275, 'prob_corte': 0.0036070394950066475}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:48:21,499] Trial 38 finished with value: 0.12495387815519203 and parameters: {'num_iterations': 1494, 'num_leaves': 63, 'feature_fraction': 0.7428964859096561, 'min_sum_hessian_in_leaf': 0.00011827609022511979, 'learning_rate': 0.01294099865918318, 'min_data_in_leaf': 210, 'scale_pos_weight': 0.7455561623283968, 'prob_corte': 0.003844787136822699}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:48:50,609] Trial 39 finished with value: 0.12135440532773767 and parameters: {'num_iterations': 800, 'num_leaves': 52, 'feature_fraction': 0.5765689861287803, 'min_sum_hessian_in_leaf': 0.022227107564179185, 'learning_rate': 0.020434923348417188, 'min_data_in_leaf': 738, 'scale_pos_weight': 0.6426104102511855, 'prob_corte': 0.006034369798332781}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:51:37,796] Trial 40 finished with value: 0.12760602115558772 and parameters: {'num_iterations': 3983, 'num_leaves': 208, 'feature_fraction': 0.4757799226122186, 'min_sum_hessian_in_leaf': 0.00014631271488491657, 'learning_rate': 0.0032948954396729005, 'min_data_in_leaf': 355, 'scale_pos_weight': 0.5404031857641385, 'prob_corte': 0.007446642965538736}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:53:14,824] Trial 41 finished with value: 0.12524590886016862 and parameters: {'num_iterations': 3818, 'num_leaves': 31, 'feature_fraction': 0.22817084864144657, 'min_sum_hessian_in_leaf': 0.004113288641142819, 'learning_rate': 0.011026601569283107, 'min_data_in_leaf': 43, 'scale_pos_weight': 0.5491293959762897, 'prob_corte': 0.007759220981925682}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:55:03,115] Trial 42 finished with value: 0.12205656782808286 and parameters: {'num_iterations': 3375, 'num_leaves': 178, 'feature_fraction': 0.6509060655572582, 'min_sum_hessian_in_leaf': 0.009115698007240651, 'learning_rate': 0.008691127884990296, 'min_data_in_leaf': 867, 'scale_pos_weight': 0.840983285622334, 'prob_corte': 0.00546828323652113}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:56:48,830] Trial 43 finished with value: 0.1209686716615101 and parameters: {'num_iterations': 3268, 'num_leaves': 1448, 'feature_fraction': 0.350713213712346, 'min_sum_hessian_in_leaf': 0.0521735839525596, 'learning_rate': 0.02478748631970695, 'min_data_in_leaf': 966, 'scale_pos_weight': 0.6417774374952818, 'prob_corte': 0.006381877252455508}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 04:58:26,016] Trial 44 finished with value: 0.11787267240155926 and parameters: {'num_iterations': 2517, 'num_leaves': 201, 'feature_fraction': 0.4432854738506248, 'min_sum_hessian_in_leaf': 0.00024251486348230174, 'learning_rate': 0.002286049949014247, 'min_data_in_leaf': 434, 'scale_pos_weight': 0.7065959971543444, 'prob_corte': 0.005754380863084873}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:00:42,371] Trial 45 finished with value: 0.1260929280870691 and parameters: {'num_iterations': 3730, 'num_leaves': 1040, 'feature_fraction': 0.4699320960634258, 'min_sum_hessian_in_leaf': 0.039905100413724956, 'learning_rate': 0.010695808478303422, 'min_data_in_leaf': 641, 'scale_pos_weight': 0.7004584878537434, 'prob_corte': 0.008557491892922903}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:02:25,611] Trial 46 finished with value: 0.11574258701998712 and parameters: {'num_iterations': 3344, 'num_leaves': 105, 'feature_fraction': 0.6386677584874023, 'min_sum_hessian_in_leaf': 0.0067199618903251435, 'learning_rate': 0.0027358139241318883, 'min_data_in_leaf': 897, 'scale_pos_weight': 0.6932296734719756, 'prob_corte': 0.007870061322885992}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:03:26,540] Trial 47 finished with value: 0.1106989955694283 and parameters: {'num_iterations': 1697, 'num_leaves': 527, 'feature_fraction': 0.5531295843145116, 'min_sum_hessian_in_leaf': 0.0009228320128650038, 'learning_rate': 0.0047680420130369015, 'min_data_in_leaf': 956, 'scale_pos_weight': 0.7403874078267186, 'prob_corte': 0.003808562712470211}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:05:35,622] Trial 48 finished with value: 0.12439596037734245 and parameters: {'num_iterations': 3374, 'num_leaves': 193, 'feature_fraction': 0.43755363814327786, 'min_sum_hessian_in_leaf': 0.007300929622893054, 'learning_rate': 0.015688225378892674, 'min_data_in_leaf': 515, 'scale_pos_weight': 0.9296052420303578, 'prob_corte': 0.004157264915714654}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:05:57,498] Trial 49 finished with value: 0.07573293066716925 and parameters: {'num_iterations': 839, 'num_leaves': 37, 'feature_fraction': 0.6849366723465027, 'min_sum_hessian_in_leaf': 0.006492838304029793, 'learning_rate': 0.002759884395466478, 'min_data_in_leaf': 806, 'scale_pos_weight': 0.8976611170895026, 'prob_corte': 0.006487820721134974}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:07:16,436] Trial 50 finished with value: 0.10888621627924701 and parameters: {'num_iterations': 2499, 'num_leaves': 42, 'feature_fraction': 0.49127245772619177, 'min_sum_hessian_in_leaf': 0.04453700487899759, 'learning_rate': 0.002922215920618493, 'min_data_in_leaf': 810, 'scale_pos_weight': 0.6694912245518236, 'prob_corte': 0.0035785630307719842}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:09:00,529] Trial 51 finished with value: 0.11990196936009438 and parameters: {'num_iterations': 3795, 'num_leaves': 19, 'feature_fraction': 0.46445724528881105, 'min_sum_hessian_in_leaf': 0.0008217767612971246, 'learning_rate': 0.024489938338322942, 'min_data_in_leaf': 697, 'scale_pos_weight': 0.8160206432054373, 'prob_corte': 0.007254216574921013}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:10:48,131] Trial 52 finished with value: 0.1214843795424582 and parameters: {'num_iterations': 3134, 'num_leaves': 472, 'feature_fraction': 0.42459989086651784, 'min_sum_hessian_in_leaf': 0.0019250405287386393, 'learning_rate': 0.013821269065594867, 'min_data_in_leaf': 824, 'scale_pos_weight': 0.5056950163371988, 'prob_corte': 0.007145513849457428}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:11:26,333] Trial 53 finished with value: 0.11265527281418654 and parameters: {'num_iterations': 1154, 'num_leaves': 204, 'feature_fraction': 0.24887089610393748, 'min_sum_hessian_in_leaf': 0.00012575920365479393, 'learning_rate': 0.006151528925873059, 'min_data_in_leaf': 612, 'scale_pos_weight': 0.8588838453606431, 'prob_corte': 0.008239914441075968}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:11:41,457] Trial 54 finished with value: 0.11059233565362638 and parameters: {'num_iterations': 466, 'num_leaves': 22, 'feature_fraction': 0.3250858919164742, 'min_sum_hessian_in_leaf': 0.00016913105771172002, 'learning_rate': 0.019969271191025286, 'min_data_in_leaf': 283, 'scale_pos_weight': 0.9647535520573389, 'prob_corte': 0.0049576786286517315}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:14:52,080] Trial 55 finished with value: 0.12995809022913363 and parameters: {'num_iterations': 2865, 'num_leaves': 957, 'feature_fraction': 0.5776488364430421, 'min_sum_hessian_in_leaf': 0.05071664346170407, 'learning_rate': 0.0035023825030570037, 'min_data_in_leaf': 108, 'scale_pos_weight': 0.5820381286882119, 'prob_corte': 0.007682306391322407}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:17:02,225] Trial 56 finished with value: 0.1293095708765538 and parameters: {'num_iterations': 2528, 'num_leaves': 1675, 'feature_fraction': 0.4991116013292942, 'min_sum_hessian_in_leaf': 0.00100559332231407, 'learning_rate': 0.005872108973205771, 'min_data_in_leaf': 198, 'scale_pos_weight': 0.9249621448268905, 'prob_corte': 0.007274899590079072}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:17:36,628] Trial 57 finished with value: 0.12439924192420744 and parameters: {'num_iterations': 882, 'num_leaves': 591, 'feature_fraction': 0.684084526101281, 'min_sum_hessian_in_leaf': 0.03309987929186149, 'learning_rate': 0.012667762186343853, 'min_data_in_leaf': 532, 'scale_pos_weight': 0.6736547052627478, 'prob_corte': 0.00767122061847143}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:19:48,104] Trial 58 finished with value: 0.13372562087428524 and parameters: {'num_iterations': 2666, 'num_leaves': 417, 'feature_fraction': 0.41493049731230947, 'min_sum_hessian_in_leaf': 0.01982600263472374, 'learning_rate': 0.0025389645718840743, 'min_data_in_leaf': 34, 'scale_pos_weight': 0.7355850855810028, 'prob_corte': 0.00616214769999174}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:20:19,359] Trial 59 finished with value: 0.12005179335422488 and parameters: {'num_iterations': 989, 'num_leaves': 61, 'feature_fraction': 0.2764930939498625, 'min_sum_hessian_in_leaf': 0.02655431771701543, 'learning_rate': 0.007947413327975994, 'min_data_in_leaf': 47, 'scale_pos_weight': 0.920430581184313, 'prob_corte': 0.005210819240460164}. Best is trial 24 with value: 0.13943876215731632.
[I 2026-10-06 05:21:38,739] Trial 60 finished with value: 0.1407301740656238 and parameters: {'num_iterations': 1786, 'num_leaves': 250, 'feature_fraction': 0.640193856976998, 'min_sum_hessian_in_leaf': 0.0421805136030512, 'learning_rate': 0.02499999999999999, 'min_data_in_leaf': 0, 'scale_pos_weight': 0.8493077974672422, 'prob_corte': 0.00540857402901119}. Best is trial 60 with value: 0.1407301740656238.
[I 2026-10-06 05:23:25,298] Trial 61 finished with value: 0.13950865811528876 and parameters: {'num_iterations': 2393, 'num_leaves': 248, 'feature_fraction': 0.6976858933359548, 'min_sum_hessian_in_leaf': 0.0979543952204965, 'learning_rate': 0.008873004298472717, 'min_data_in_leaf': 0, 'scale_pos_weight': 0.9847356288063256, 'prob_corte': 0.005255490495358751}. Best is trial 60 with value: 0.1407301740656238.
[I 2026-10-06 05:25:49,570] Trial 62 finished with value: 0.12992585431276585 and parameters: {'num_iterations': 1743, 'num_leaves': 2048, 'feature_fraction': 0.7499999999999999, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.025, 'min_data_in_leaf': 0, 'scale_pos_weight': 0.5241731076818954, 'prob_corte': 0.005709028319559231}. Best is trial 60 with value: 0.1407301740656238.
[I 2026-10-06 05:26:49,297] Trial 63 finished with value: 0.13696548705776976 and parameters: {'num_iterations': 1875, 'num_leaves': 169, 'feature_fraction': 0.14772484679349057, 'min_sum_hessian_in_leaf': 0.09999999999999998, 'learning_rate': 0.025, 'min_data_in_leaf': 0, 'scale_pos_weight': 0.8642099948787048, 'prob_corte': 0.005765516650855498}. Best is trial 60 with value: 0.1407301740656238.
[I 2026-10-06 05:28:15,736] Trial 64 finished with value: 0.14325195604665278 and parameters: {'num_iterations': 2164, 'num_leaves': 192, 'feature_fraction': 0.7499999999999999, 'min_sum_hessian_in_leaf': 0.0009232344831679066, 'learning_rate': 0.025, 'min_data_in_leaf': 0, 'scale_pos_weight': 0.7117868274336769, 'prob_corte': 0.005080292533901142}. Best is trial 64 with value: 0.14325195604665278.
[I 2026-10-06 05:29:44,042] Trial 65 finished with value: 0.14036454773484772 and parameters: {'num_iterations': 2448, 'num_leaves': 153, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.025, 'min_data_in_leaf': 0, 'scale_pos_weight': 0.5, 'prob_corte': 0.005737413886108825}. Best is trial 64 with value: 0.14325195604665278.
[I 2026-10-06 05:33:35,118] Trial 66 finished with value: 0.13820024780753282 and parameters: {'num_iterations': 4000, 'num_leaves': 428, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.1, 'learning_rate': 0.0025990973667086785, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0, 'prob_corte': 0.0035446538114082874}. Best is trial 64 with value: 0.14325195604665278.
[I 2026-10-06 05:35:16,305] Trial 67 finished with value: 0.1423124986271084 and parameters: {'num_iterations': 2341, 'num_leaves': 240, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.025, 'min_data_in_leaf': 0, 'scale_pos_weight': 0.6563269656147925, 'prob_corte': 0.008394219062929857}. Best is trial 64 with value: 0.14325195604665278.
[I 2026-10-06 05:37:07,756] Trial 68 finished with value: 0.1440771775423547 and parameters: {'num_iterations': 2543, 'num_leaves': 239, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.025, 'min_data_in_leaf': 0, 'scale_pos_weight': 0.5564284424059784, 'prob_corte': 0.0035446538114082874}. Best is trial 68 with value: 0.1440771775423547.
[I 2026-10-06 05:39:14,919] Trial 69 finished with value: 0.14239401910869043 and parameters: {'num_iterations': 2607, 'num_leaves': 301, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.025, 'min_data_in_leaf': 0, 'scale_pos_weight': 0.8231718607910654, 'prob_corte': 0.00368897755965802}. Best is trial 68 with value: 0.1440771775423547.
[I 2026-10-06 05:40:52,363] Trial 70 finished with value: 0.14394795600020538 and parameters: {'num_iterations': 2125, 'num_leaves': 264, 'feature_fraction': 0.75, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.025, 'min_data_in_leaf': 0, 'scale_pos_weight': 0.5, 'prob_corte': 0.004379194199040686}. Best is trial 68 with value: 0.1440771775423547.

## Resultados de la optimización

In [33]:
tb_bayesiana = study.trials_dataframe()
tb_bayesiana["iter"] = np.arange(1, len(tb_bayesiana) + 1)
tb_bayesiana = (
    tb_bayesiana
    .sort_values("value", ascending=False, na_position="last")
    .reset_index(drop=True)
)
tb_bayesiana.to_csv(
    os.path.join(EXPERIMENT_URL, "BO_log.txt"),
    sep="	",
    index=False,
)

prob_corte_optimo = float(study.best_trial.params["prob_corte"])
# PARAM.yml conserva los HP de LightGBM; el corte queda en BO_log.txt y resumen.md.
PARAM["out"]["lgbm"]["mejores_hiperparametros"] = {
    nombre: valor for nombre, valor in study.best_trial.params.items()
    if nombre != "prob_corte"
}
PARAM["out"]["lgbm"]["y"] = float(study.best_value)

with open(os.path.join(EXPERIMENT_URL, "PARAM.yml"), "w", encoding="utf-8") as archivo:
    yaml.safe_dump(PARAM, archivo, sort_keys=False, allow_unicode=True)

print(PARAM["out"]["lgbm"]["mejores_hiperparametros"])
print("Mejor Average Precision:", PARAM["out"]["lgbm"]["y"])
tb_bayesiana.head()

{'num_iterations': 3668, 'num_leaves': 204, 'feature_fraction': 0.3847092908193044, 'min_sum_hessian_in_leaf': 0.00010000000000000009, 'learning_rate': 0.025, 'min_data_in_leaf': 0, 'scale_pos_weight': 1.0}
Mejor Average Precision: 0.146249656032765

,number,value,datetime_start,datetime_complete,duration,params_feature_fraction,params_learning_rate,params_min_data_in_leaf,params_min_sum_hessian_in_leaf,params_num_iterations,params_num_leaves,params_prob_corte,params_scale_pos_weight,system_attrs_fixed_params,system_attrs_gp:relative_params:0,state,iter
0,141,0.146250,2026-10-06 08:21:57.544136,2026-10-06 08:24:18.012466,0 days 00:02:20.468330,0.384709,0.025000,0,0.0001,3668,204,0.003545,1.000000,NaN,"{""feature_fraction"": 0.3847092908193044, ""lear...",COMPLETE,142
1,152,0.145880,2026-10-06 08:46:26.084876,2026-10-06 08:48:51.364112,0 days 00:02:25.279236,0.462775,0.025000,0,0.0001,3362,251,0.003545,1.000000,NaN,"{""feature_fraction"": 0.4627750965022953, ""lear...",COMPLETE,153
2,110,0.145262,2026-10-06 06:59:45.151364,2026-10-06 07:01:41.336560,0 days 00:01:56.185196,0.330960,0.025000,0,0.0001,3084,227,0.008646,0.754676,NaN,"{""feature_fraction"": 0.33095966855765835, ""lea...",COMPLETE,111
3,150,0.144967,2026-10-06 08:42:20.262415,2026-10-06 08:44:57.724248,0 days 00:02:37.461833,0.426132,0.013923,0,0.0001,3658,247,0.003545,1.000000,NaN,"{""feature_fraction"": 0.4261322704767676, ""lear...",COMPLETE,151
4,184,0.144960,2026-10-06 09:59:13.879514,2026-10-06 10:01:27.896578,0 days 00:02:14.017064,0.345427,0.025000,0,0.0001,3609,199,0.005957,1.000000,NaN,"{""feature_fraction"": 0.34542727310493715, ""lea...",COMPLETE,185

## Producción: marzo a julio para predecir agosto

In [34]:
dataset_final_cpu = (
    df_completo
    .loc[df_completo["foto_mes"].isin(PARAM["train_final"])]
    .to_pandas()
    .reset_index(drop=True)
)
etiquetas_julio = etiquetar_julio(prob_corte_optimo)
dataset_final_cpu.loc[
    dataset_final_cpu["foto_mes"].isin(meses_julio), "ternaria"
] = etiquetas_julio
dataset_final_cpu["clase01"] = (
    dataset_final_cpu["ternaria"].isin(["BAJA+1", "BAJA+2"])
    .astype(np.int8)
)

dataset_final_cpu.groupby(["foto_mes", "ternaria"]).size()

foto_mes  ternaria
202103    BAJA+1        1019
          BAJA+2         960
          continua    160921
202104    BAJA+1         964
          BAJA+2        1139
          continua    161181
202105    BAJA+1        1143
          BAJA+2         870
          continua    161755
202106    BAJA+1         874
          BAJA+2        1098
          continua    162142
202107    BAJA+1        1103
          BAJA+2       15000
          CONTINUA    148245
dtype: int64

In [35]:
param_final = {
    **PARAM["lgbm"]["param_fijos"],
    **PARAM["out"]["lgbm"]["mejores_hiperparametros"],
}

num_boost_round_final = int(param_final.pop("num_iterations"))
param_final["min_data_in_leaf"] = round(
    param_final["min_data_in_leaf"] / PARAM["trainingstrategy"]["undersampling"]
)
param_final

dtrain_final = lgb.Dataset(
    data=dataset_final_cpu[campos_buenos],
    label=dataset_final_cpu["clase01"],
    feature_name=campos_buenos,
)

modelo_final = lgb.train(
    params=param_final,
    train_set=dtrain_final,
    num_boost_round=num_boost_round_final,
)

In [36]:
arboles_df = modelo_final.trees_to_dataframe()
splits_df = arboles_df.loc[arboles_df["split_feature"].notna()]

tb_importancia = (
    splits_df
    .groupby("split_feature", as_index=False)
    .agg(
        Gain=("split_gain", "sum"),
        Cover=("count", "sum"),
        Frequency=("split_feature", "size"),
    )
    .rename(columns={"split_feature": "Feature"})
)

for columna in ["Gain", "Cover", "Frequency"]:
    total = tb_importancia[columna].sum()
    if total > 0:
        tb_importancia[columna] = tb_importancia[columna] / total

tb_importancia = tb_importancia.sort_values("Gain", ascending=False)
tb_importancia.to_csv(
    os.path.join(EXPERIMENT_URL, "impo.txt"),
    sep="\t",
    index=False,
)
modelo_final.save_model(os.path.join(EXPERIMENT_URL, "modelo.txt"))

tb_importancia.head(20)

                                      Feature      Gain     Cover  Frequency
302                                  foto_mes  0.069418  0.046140   0.003063
299                              ctrx_quarter  0.058902  0.009284   0.009496
301                     ctrx_quarter_lag_pond  0.055465  0.002695   0.004911
318                              mcaja_ahorro  0.044606  0.008998   0.009406
389                                  mpayroll  0.042485  0.009676   0.002840
234                              cpayroll_trx  0.026729  0.006138   0.001904
122                          Visa_msaldopesos  0.023569  0.003968   0.005579
215         cliente_antiguedad_delta_lag_pond  0.023086  0.011692   0.005749
359                            mcuentas_saldo  0.021195  0.016360   0.012123
421                     mtarjeta_visa_consumo  0.020363  0.004470   0.004127
16            Master_fechaalta_delta_lag_pond  0.012656  0.001654   0.004291
386                           mpasivos_margen  0.012638  0.006261   0.009872
410                      mrentabilidad_annual  0.011643  0.019421   0.016080
110                          Visa_mpagominimo  0.011237  0.004525   0.006990
82              Visa_fechaalta_delta_lag_pond  0.011109  0.002321   0.004307
346  mcomisiones_mantenimiento_delta_lag_pond  0.010877  0.003270   0.004365
306                           mactivos_margen  0.010408  0.009241   0.012280
351                         mcuenta_corriente  0.010092  0.012970   0.013450
405            mprestamos_personales_lag_pond  0.009911  0.018858   0.005365
388                  mpasivos_margen_lag_pond  0.009614  0.001690   0.005091

In [37]:
dfuture_cpu = (
    df_completo
    .loc[df_completo["foto_mes"].isin(PARAM["future"])]
    .to_pandas()
    .reset_index(drop=True)
)

prediccion = modelo_final.predict(dfuture_cpu[campos_buenos])

tb_prediccion = dfuture_cpu[["numero_de_cliente", "foto_mes", "ternaria"]].copy()
tb_prediccion["prob"] = prediccion
tb_prediccion[["numero_de_cliente", "foto_mes", "prob"]].to_csv(
    os.path.join(EXPERIMENT_URL, "prediccion.txt"),
    sep="\t",
    index=False,
)

tb_prediccion.head()

   numero_de_cliente  foto_mes ternaria          prob
0           12159854    202108      NaN  8.724335e-06
1           12159858    202108      NaN  3.630242e-06
2           12160484    202108      NaN  1.276281e-07
3           12160591    202108      NaN  1.425858e-08
4           12160747    202108      NaN  6.819066e-07

In [38]:
with open(os.path.join(EXPERIMENT_URL, "PARAM.yml"), "w", encoding="utf-8") as archivo:
    yaml.safe_dump(PARAM, archivo, sort_keys=False, allow_unicode=True)

## Documentación de la segunda BO

In [39]:
clase_julio = np.isin(etiquetas_julio, ["BAJA+1", "BAJA+2"])
training_julio = (
    (azar_julio <= PARAM["trainingstrategy"]["undersampling"])
    | clase_julio
)
contenido_md = [
    f"# Resumen — {experiment_name}",
    "",
    "- Etiquetas: reales en marzo a junio y BAJA+1 de julio; BAJA+2 estimadas en julio.",
    "- Julio participa solamente en el entrenamiento, no en la validación.",
    f"- Meses de validación: {', '.join(map(str, meses_reales))}",
    "- Validación: se conserva dvalidate de la primera BO, con etiquetas reales.",
    f"- Experimento que generó las probabilidades de julio: `{experimento_origen}`",
    "- Probabilidades por cliente y mes: `predicciones_julio/prediccion.txt`.",
    "- Estas probabilidades corresponden a la clase conjunta BAJA+1/BAJA+2 del primer modelo.",
    f"- Meses con BAJA+2 estimadas: {', '.join(map(str, meses_julio))}",
    "- Regla: conservar BAJA+1 real; asignar BAJA+2 si prob >= prob_corte; CONTINUA en el resto.",
    f"- Puestos para definir el rango: {min(PARAM['cortes'])} a {max(PARAM['cortes'])}, excluyendo BAJA+1 conocidas.",
    f"- Rango de prob_corte: {rangos_bo['prob_corte']}",
    f"- Mejor prob_corte: {prob_corte_optimo}",
    f"- BAJA+1 reales conservadas en julio: {int(baja1_julio.sum())}",
    f"- BAJA+2 estimadas en julio: {int((etiquetas_julio == 'BAJA+2').sum())}",
    f"- Registros de entrenamiento BO con el mejor corte: {len(X_train_bo) + int(training_julio.sum())}",
    f"- Registros de validación BO: {len(X_validate_bo)}",
    f"- Registros de entrenamiento final: {len(dataset_final_cpu)}",
    f"- Registros predichos: {len(dfuture_cpu)}",
    "- Agosto no tiene BAJA+2 real: no se calcula ganancia sobre ese mes.",
    f"- Dataset: `{dataset_file}`",
    f"- Meses de entrenamiento: {', '.join(map(str, PARAM['train']))}",
    f"- Meses de entrenamiento final: {', '.join(map(str, PARAM['train_final']))}",
    f"- Meses a predecir: {', '.join(map(str, PARAM['future']))}",
    f"- Semilla: {PARAM['semilla_primigenia']}",
    "- Clase positiva: BAJA+1 y BAJA+2.",
    f"- Columnas excluidas: {', '.join(sorted(columnas_excluidas))}",
    f"- Porcentaje para entrenamiento en el split: {PARAM['training_pct']}",
    f"- Undersampling: {PARAM['trainingstrategy']['undersampling']}",
    f"- Corridas por BO: {PARAM['hyperparametertuning']['iteraciones']}",
    f"- Inicializaciones totales: {PARAM['hyperparametertuning']['n_startup_trials']}",
    f"- Inicializaciones desde RDS: {len(puntos_iniciales_bo)}",
    f"- Inicializaciones aleatorias: {PARAM['hyperparametertuning']['n_startup_trials'] - len(puntos_iniciales_bo)}",
    f"- Fuente de las inicializaciones: `{archivo_validaciones}`",
    f"- IDs de validación usados: {', '.join(map(str, modelos_iniciales['id_validacion']))}",
    "- Selección: mayor ganancia dentro del dataset actual; se completa con los demás datasets.",
    "- min_data_in_leaf de los RDS: se revierte el ajuste por undersampling antes de inicializar.",
    f"- Rangos de HP: `{rangos_bo}`",
    f"- Mejor trial de Optuna: {study.best_trial.number}",
    f"- Mejor Average Precision: {PARAM['out']['lgbm']['y']}",
    f"- Mejores HP: `{PARAM['out']['lgbm']['mejores_hiperparametros']}`",
]
with open(os.path.join(EXPERIMENT_URL, "resumen.md"), "w", encoding="utf-8") as archivo:
    archivo.write("\n".join(contenido_md) + "\n")