# Librerias

In [14]:
# cargo las librerias que necesito
require("data.table")
require("lightgbm")
library(data.table)

# URLS

Ejecutar con el directorio de trabajo en `entregas/`.

In [15]:
carpeta_entregas <- getwd()
data_folder <- file.path(carpeta_entregas, "dataset")
carpeta_parametros <- file.path(carpeta_entregas, "parametros")
carpeta_salida <- file.path(carpeta_entregas, "entregas")
archivo_logging <- file.path(carpeta_entregas, "logging.csv")

# Parametrizacion de la prueba

Completar el mes a predecir, el ID del `.rds` y la cantidad de envios antes de ejecutar. Revisar los meses de entrenamiento.

In [16]:
files = list.files(data_folder)
cat(files, sep = "\n")

c_01_tern_2_lags_O2.csv
c_01_tern_2_lags.csv
c_01_tern_2_lf_k6_p4.csv
c_01_tern_2_lf_O2_k3_p6.csv
c_01_tern_2.csv
competencia_01_crudo.csv
competencia_01_ternaria_lags.csv
competencia_01_ternaria_lf_k6_perdida4.csv
competencia_01_ternaria.csv
versiones_dataset_1.ipynb
versiones_dataset_2.ipynb

In [17]:
# dataset_file <- "competencia_01_ternaria_lags.csv"
# dataset_file <- "competencia_01_ternaria_lf_k6_perdida4.csv"
dataset_file <- "c_01_tern_2_lf_k6_p4.csv"

train_final <- c(202103, 202104,202105, 202106)
future <- 202108  # mes a predecir
SEEDS <- c(230047, 230059, 230063, 230077, 230081)

id_rds <- 44  # archivo parametros/<id_rds>.rds
envios <- 11000 # cantidad de clientes con Predicted = 1

In [18]:

columnas_excluir <- c(
    "ternaria",
    'ternaria_lag1',
    "clase01",
    "fold",
    "azar",
    "training",
    'cprestamos_personales',
    'mprestamos_personales',
    'cprestamos_personales_lag1',
    'mprestamos_personales_lag1',
    'cprestamos_personales_delta1',
    'mprestamos_personales_delta1',
    'cprestamos_personales_lag_pond',
    'mprestamos_personales_lag_pond',
    'cprestamos_personales_delta_lag_pond',
    'mprestamos_personales_delta_lag_pond'
)

if (anyNA(c(future, id_rds, envios))) {
  stop("Completar future, id_rds y envios en esta celda.")
}

# LEEMOS DATASET

In [19]:
dataset_url <- file.path(data_folder, dataset_file)
dataset <- fread(dataset_url)

setorder(dataset, foto_mes, ternaria, numero_de_cliente)
dataset[, .N, list(foto_mes, ternaria)]

   foto_mes ternaria N
1  202103   BAJA+1     1019
2  202103   BAJA+2      960
3  202103   continua 160921
4  202104   BAJA+1      964
5  202104   BAJA+2     1139
6  202104   continua 161181
7  202105   BAJA+1     1143
8  202105   BAJA+2      870
9  202105   continua 161755
10 202106   BAJA+1      874
11 202106   BAJA+2     1098
12 202106   continua 162142
13 202107            163245
14 202107   BAJA+1     1103
15 202108            164647

# Parametros

El `.rds` debe estar copiado en `parametros/`. Se usan los parametros guardados, sin volver a ajustar `min_data_in_leaf`.

In [20]:
parametros <- readRDS(
  file.path(carpeta_parametros, paste0(id_rds, ".rds"))
)

# Dataset train y prediccion

In [21]:
dataset[, clase01 := ifelse(ternaria %in% c("BAJA+1", "BAJA+2"), 1L, 0L)]

campos_buenos <- setdiff(colnames(dataset), columnas_excluir)

dataset_train <- dataset[foto_mes %in% train_final]
dfuture <- dataset[foto_mes %in% future]

if (length(future) != 1L || nrow(dataset_train) == 0L ||
    nrow(dfuture) == 0L || envios < 1L || envios > nrow(dfuture) ||
    envios != as.integer(envios)) {
  stop("Revisar meses y envios: se requiere un mes a predecir y filas en ambos datasets.")
}

dataset_train[, .N, list(foto_mes, ternaria)]

   foto_mes ternaria N
1  202103   BAJA+1     1019
2  202103   BAJA+2      960
3  202103   continua 160921
4  202104   BAJA+1      964
5  202104   BAJA+2     1139
6  202104   continua 161181
7  202105   BAJA+1     1143
8  202105   BAJA+2      870
9  202105   continua 161755
10 202106   BAJA+1      874
11 202106   BAJA+2     1098
12 202106   continua 162142

# Entreno y genero salidas

Se conserva solamente el CSV actual de cada semilla.

In [22]:
if (file.exists(archivo_logging)) {
  historico <- fread(archivo_logging)
  id_prueba <- max(historico$id_prueba) + 1L
} else {
  id_prueba <- 1L
}

dir.create(carpeta_salida, recursive= TRUE, showWarnings= FALSE)
archivos_salida <- character(length(SEEDS))

for (i in seq_along(SEEDS)) {
  # El .rds puede contener parametros individuales o una lista por semilla.
  if ("num_iterations" %in% names(parametros)) {
    params_semilla <- parametros
  } else {
    params_semilla <- parametros[[as.character(SEEDS[i])]]
    if (is.null(params_semilla)) {
      stop("El .rds no contiene parametros para la semilla ", SEEDS[i])
    }
  }
  params_semilla$seed <- SEEDS[i]

  dtrain_final <- lgb.Dataset(
    data= data.matrix(dataset_train[, campos_buenos, with= FALSE]),
    label= dataset_train[, clase01]
  )

  modelo_final <- lgb.train(
    data= dtrain_final,
    param= params_semilla
  )

  prediccion <- predict(
    modelo_final,
    data.matrix(dfuture[, campos_buenos, with= FALSE])
  )

  tb_prediccion <- dfuture[, list(numero_de_cliente)]
  tb_prediccion[, prob := prediccion]
  setorder(tb_prediccion, -prob)
  tb_prediccion[, Predicted := 0L]
  tb_prediccion[1:envios, Predicted := 1L]

  # archivos_salida[i] <- paste0("r001_", SEEDS[i], ".csv")
  archivos_salida[i] <- paste0("r001_", SEEDS[i],"_", id_prueba, ".csv")

  fwrite(
    tb_prediccion[Predicted == 1L, list(numero_de_cliente)],
    file.path(carpeta_salida, archivos_salida[i]),
    sep= ",",
    col.names= FALSE
  )

  cat("Semilla=", SEEDS[i], " Archivo=", archivos_salida[i], "\n", sep= "")
}

Semilla=230047 Archivo=r001_230047_13.csv
Semilla=230059 Archivo=r001_230059_13.csv
Semilla=230063 Archivo=r001_230063_13.csv
Semilla=230077 Archivo=r001_230077_13.csv
Semilla=230081 Archivo=r001_230081_13.csv

# Documentacion de la prueba

Una fila por ejecucion, con todas las semillas usadas. Completar la nota y el resultado de Kaggle como texto. Cuando llegue el resultado, ejecutar solamente esta celda: actualiza la misma fila y conserva las pruebas anteriores.

In [23]:
#lets stop here
pepe

ERROR: Error in eval(expr, envir, enclos): object 'pepe' not found

In [24]:
nota <- "agregamos otro mes al entrenamiento dataset fraccionario con nan en ccajas_depositos para 202105"
resultado_competencia_mean <- "102.9930"  # score de Kaggle o referencia a un problema con la entrega
resultado_competencia_std <- "4.0862"
ref_submit <- 'e13_rbis'

In [25]:

registro_prueba <- data.table(
  id_prueba = id_prueba,
  ref_submit = ref_submit,
  notebook = "r001.ipynb",
  dataset = dataset_file,
  seeds = paste(SEEDS, collapse = ","),
  cantidad_registros_totales = nrow(dataset),
  cantidad_registros_entrenamiento = nrow(dataset_train),
  cantidad_registros_prediccion = nrow(dfuture),
  meses_entrenamiento = paste(train_final, collapse = ","),
  meses_prediccion = paste(future, collapse = ","),
  columnas_excluidas = paste(columnas_excluir, collapse = ","),
  "bajas" = "1+2",                                       #baja+1 y baja+2 o solo baja+2
  id_rds = id_rds,
  envios = envios,
  archivos = paste(archivos_salida, collapse = ","),
  nota = nota,
  resultado_competencia_mean = resultado_competencia_mean,
  resultado_competencia_std = resultado_competencia_std
)

if (file.exists(archivo_logging)) {
  historico <- fread(
    archivo_logging,
    colClasses = list(character = c("nota", "resultado_competencia_mean"))
  )
  fila <- which(historico$id_prueba == id_prueba)

  if (length(fila) > 0L) {
    historico[fila, (names(registro_prueba)) := registro_prueba]
    fwrite(historico, archivo_logging)
  } else {
    fwrite(registro_prueba, archivo_logging, append = TRUE, col.names = FALSE)
  }
} else {
  fwrite(registro_prueba, archivo_logging)
}

In [26]:

# registro_prueba
tail(fread(archivo_logging), 10)

   id_prueba ref_submit notebook   dataset
1   4        e4_r       r001.ipynb competencia_01_ternaria_lf_k6_perdida4.csv
2   5        e5_r       r001.ipynb competencia_01_ternaria_lf_k6_perdida4.csv
3   6        e6_r       r001.ipynb competencia_01_ternaria_lf_k6_perdida4.csv
4   7        e7_r       r001.ipynb competencia_01_ternaria_lf_k6_perdida4.csv
5   8        e8_r       r002.ipynb competencia_01_ternaria_lf_k6_perdida4.csv
6   9        e9_r       r002.ipynb competencia_01_ternaria_lf_k6_perdida4.csv
7  10        e10_r      r002.ipynb competencia_01_ternaria_lf_k6_perdida4.csv
8  11        e11_r      r001.ipynb c_01_tern_2_lf_k6_p4.csv
9  12        e12_r      r001.ipynb c_01_tern_2_lf_k6_p4.csv
10 13        e13_rbis   r001.ipynb c_01_tern_2_lf_k6_p4.csv
   seeds                              cantidad_registros_totales
1  230047,230059,230063,230077,230081 983061
2  230047,230059,230063,230077,230081 983061
3  230047,230059,230063,230077,230081 983061
4  230047,230059,230063,230077,230081 983061
5  230047,230059,230063,230077,230081 983061
6  230047,230059,230063,230077,230081 983061
7  230047,230059,230063,230077,230081 983061
8  230047,230059,230063,230077,230081 983061
9  230047,230059,230063,230077,230081 983061
10 230047,230059,230063,230077,230081 983061
   cantidad_registros_entrenamiento cantidad_registros_prediccion
1  326184                           164647
2  326184                           164647
3  326184                           164647
4  326184                           164647
5  818414                           164647
6  818414                           164647
7  818414                           164647
8  489952                           164647
9  654066                           164647
10 654066                           164647
   meses_entrenamiento                meses_prediccion
1  202103,202104                      202108
2  202103,202104                      202108
3  202103,202104                      202108
4  202103,202104                      202108
5  202103,202104,202105,202106,202107 202108
6  202103,202104,202105,202106,202107 202108
7  202103,202104,202105,202106,202107 202108
8  202103,202104,202105               202108
9  202103,202104,202105,202106        202108
10 202103,202104,202105,202106        202108
   columnas_excluidas
1  ternaria,ternaria_lag1,clase01,fold,azar,training,cprestamos_personales,mprestamos_personales,cprestamos_personales_lag1,mprestamos_personales_lag1,cprestamos_personales_delta1,mprestamos_personales_delta1,cprestamos_personales_lag_pond,mprestamos_personales_lag_pond,cprestamos_personales_delta_lag_pond,mprestamos_personales_delta_lag_pond
2  ternaria,ternaria_lag1,clase01,fold,azar,training,cprestamos_personales,mprestamos_personales,cprestamos_personales_lag1,mprestamos_personales_lag1,cprestamos_personales_delta1,mprestamos_personales_delta1,cprestamos_personales_lag_pond,mprestamos_personales_lag_pond,cprestamos_personales_delta_lag_pond,mprestamos_personales_delta_lag_pond
3  ternaria,ternaria_lag1,clase01,fold,azar,training,cprestamos_personales,mprestamos_personales,cprestamos_personales_lag1,mprestamos_personales_lag1,cprestamos_personales_delta1,mprestamos_personales_delta1,cprestamos_personales_lag_pond,mprestamos_personales_lag_pond,cprestamos_personales_delta_lag_pond,mprestamos_personales_delta_lag_pond
4  ternaria,ternaria_lag1,clase01,fold,azar,training,cprestamos_personales,mprestamos_personales,cprestamos_personales_lag1,mprestamos_personales_lag1,cprestamos_personales_delta1,mprestamos_personales_delta1,cprestamos_personales_lag_pond,mprestamos_personales_lag_pond,cprestamos_personales_delta_lag_pond,mprestamos_personales_delta_lag_pond
5  ternaria,ternaria_lag1,clase01,fold,azar,training,cprestamos_personales,mprestamos_personales,cprestamos_personales_lag1,mprestamos_personales_lag1,cprestamos_personales_delta1,mprestamos_personales_delta1
6  ternaria,ternaria_lag1,clase01,fold,azar,training,cprestamos_personales,mprestamos_personales,cprestamos_personales_lag1,mprestamos_personales_lag1,cprestamos_personales_delta1,mprestamos_personales_delta1
7  ternaria,ternaria_lag1,clase01,fold,azar,training,cprestamos_personales,mprestamos_personales,cprestamos_personales_lag1,mprestamos_personales_lag1,cprestamos_personales_delta1,mprestamos_personales_delta1
8  ternaria,ternaria_lag1,clase01,fold,azar,training,cprestamos_personales,mprestamos_personales,cprestamos_personales_lag1,mprestamos_personales_lag1,cprestamos_personales_delta1,mprestamos_personales_delta1,cprestamos_personales_lag_pond,mprestamos_personales_lag_pond,cprestamos_personales_delta_lag_pond,mprestamos_personales_delta_lag_pond
9  ternaria,ternaria_lag1,clase01,fold,azar,training,cprestamos_personales,mprestamos_personales,cprestamos_personales_lag1,mprestamos_personales_lag1,cprestamos_personales_delta1,mprestamos_personales_delta1,cprestamos_personales_lag_pond,mprestamos_personales_lag_pond,cprestamos_personales_delta_lag_pond,mprestamos_personales_delta_lag_pond
10 ternaria,ternaria_lag1,clase01,fold,azar,training,cprestamos_personales,mprestamos_personales,cprestamos_personales_lag1,mprestamos_personales_lag1,cprestamos_personales_delta1,mprestamos_personales_delta1,cprestamos_personales_lag_pond,mprestamos_personales_lag_pond,cprestamos_personales_delta_lag_pond,mprestamos_personales_delta_lag_pond
   bajas id_rds envios
1  1+2   44     11500
2  1+2   44     12000
3  1+2   44     11000
4  1+2   44     10500
5  1+2   53     10500
6  1+2   53     11500
7  1+2   53     12500
8  1+2   44     10500
9  1+2   44     10500
10 1+2   44     11000
   archivos
1  r001_230047_4.csv,r001_230059_4.csv,r001_230063_4.csv,r001_230077_4.csv,r001_230081_4.csv
2  r001_230047_5.csv,r001_230059_5.csv,r001_230063_5.csv,r001_230077_5.csv,r001_230081_5.csv
3  r001_230047_6.csv,r001_230059_6.csv,r001_230063_6.csv,r001_230077_6.csv,r001_230081_6.csv
4  r001_230047_7.csv,r001_230059_7.csv,r001_230063_7.csv,r001_230077_7.csv,r001_230081_7.csv
5  r002_230047_8.csv,r002_230059_8.csv,r002_230063_8.csv,r002_230077_8.csv,r002_230081_8.csv
6  r002_230047_9.csv,r002_230059_9.csv,r002_230063_9.csv,r002_230077_9.csv,r002_230081_9.csv
7  r002_230047_10.csv,r002_230059_10.csv,r002_230063_10.csv,r002_230077_10.csv,r002_230081_10.csv
8  r001_230047_11.csv,r001_230059_11.csv,r001_230063_11.csv,r001_230077_11.csv,r001_230081_11.csv
9  r001_230047_12.csv,r001_230059_12.csv,r001_230063_12.csv,r001_230077_12.csv,r001_230081_12.csv
10 r001_230047_13.csv,r001_230059_13.csv,r001_230063_13.csv,r001_230077_13.csv,r001_230081_13.csv
   nota
1  cambiamos dataset al q se uso en rds 44, deltas fraccionarios
2  e4_r pasando de 11.5k envios a 12k envios
3  e4_r pasando de 11.5k envios a 11k envios
4  e4_r pasando de 11.5k envios a 10.5k envios
5  BO para predecir b+2 en 202107 y usada para entrenar para 202108 | BAJA+2 estimadas para 202107; id_rds_julio=52; meses_entrenamiento_julio=202103,202104,202105,202106; seed_julio=230047; prob_corte=0.0035446538114082874; BAJA+1 reales=1103; BAJA+2 estimadas=14888
6  e8_r subiendo la cantidad de envios a 11.5 k | BAJA+2 estimadas para 202107; id_rds_julio=52; meses_entrenamiento_julio=202103,202104,202105,202106; seed_julio=230047; prob_corte=0.0035446538114082874; BAJA+1 reales=1103; BAJA+2 estimadas=14888
7  e8_r subiendo la cantidad de envios a 12.5 k | BAJA+2 estimadas para 202107; id_rds_julio=52; meses_entrenamiento_julio=202103,202104,202105,202106; seed_julio=230047; prob_corte=0.0035446538114082874; BAJA+1 reales=1103; BAJA+2 estimadas=14888
8  agregamos 1 mes al entrenamiento dataset fraccionario con nan en ccajas_depositos para 202105
9  agregamos otro mes al entrenamiento dataset fraccionario con nan en ccajas_depositos para 202105
10 agregamos otro mes al entrenamiento dataset fraccionario con nan en ccajas_depositos para 202105
   resultado_competencia_mean resultado_competencia_std
1   95.2215                   1.7673
2   95.3095                   2.2131
3   95.7825                   1.9090
4   95.3535                   2.3168
5   91.3055                   4.8356
6   92.4220                   4.3839
7   91.9820                   4.2977
8   98.3455                   2.0969
9  102.4100                   1.8183
10 102.9930                   4.0862